on: [push]
jobs:
  test:
    runs-on: ubuntu-go-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Test for tidy, fmt, vet
        run: |
          echo '--- Begin "go mod tidy"'
          if go mod tidy -diff; then printf -- '--- \U0001f7e9 "go.mod" is tidy.'; else printf -- "--- \U0001f7e5 Exit code: $?, "go.mod" is not tidy!"; fi
          echo '--- Begin "gofmt -l"'
          out=$(gofmt -l .)
          exit_code=$?
          if test -z $out; then printf -- '--- \U0001f7e9 Source files are formatted.'; else echo -e "Unformatted files:\n$out; printf -- "--- \U0001f7e5 Exit code: $exit_code, Source is unformatted!"; exit $exit_code; fi
          echo '--- Begin "go vet ./..."'
          if go vet ./...; then printf -- '--- \U0001f7e9 No suspicious constructs found.'; else printf "--- \U0001f7e5 Exit code: $?, Suspicious constructs found!"; fi
      - name: Lint
        uses: golangci/golangci-lint-action@v9
      - name: Unit Tests
        run: |
          echo '--- Begin unit testing'
          if CGO_ENABLED=0 go test ./...; then printf -- '--- \U0001f7e9 Unit tests passed.'; else printf -- "--- \U0001f7e5 Exit code: $?, Unit tests failed!"; fi
