on: [push]
jobs:
  test:
    runs-on: ubuntu-go-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Test for tidy, fmt, vet
        run: |
          function message() {
            if [ $1 = 'info' ]; then
              printf -- "--- \U0001f7e6 $2\n";
            else
              if eval $2; then
                printf -- "--- \U0001f7e9 $3\n";
              else
                exit_code=$?
                printf -- "--- \U0001f7e5 Exit code: $exit_code, $4\n";
                exit $exit_code
              fi
            fi
          }

          message info 'Begin "go mod tidy"'
          message exec 'go mod tidy -diff' '"go.mod" is tidy.' '"go.mod" is not tidy!'

          message info 'Begin "gofmt -l"'
          message exec 'test -z $(gofmt -l .)' 'Source files are formatted.' 'Source is unformatted!'

          message info 'Begin "go vet ./..."'
          message exec 'go vet ./...' 'No suspicious constructs found.' 'Suspicious constructs found!'
      - name: Lint
        uses: golangci/golangci-lint-action@v9
      - name: Unit Tests
        run: |
          message info 'Begin unit testing'
          message 'CGO_ENABLED go test ./...' 'Unit tests passed.'Unit tests failed!'
