package aws

// Resource type constants for all AWS resource types discovered by this provider.
// Using constants prevents typos in scanner and resolver files — a mismatched
// string would create orphan resources with an undeclared type.
const (
	// EC2 — compute management (ec2_compute_mgmt_scanners.go)
	TypeEC2Instance                = "aws:ec2:instance"
	TypeEC2Image                   = "aws:ec2:image"
	TypeEC2SecurityGroup           = "aws:ec2:security-group"
	TypeEC2Volume                  = "aws:ec2:volume"
	TypeEC2LaunchTemplate          = "aws:ec2:launch-template"
	TypeEC2KeyPair                 = "aws:ec2:key-pair"
	TypeEC2PlacementGroup          = "aws:ec2:placement-group"
	TypeEC2SpotFleet               = "aws:ec2:spot-fleet"
	TypeEC2Host                    = "aws:ec2:host"
	TypeEC2CapacityReservation     = "aws:ec2:capacity-reservation"
	TypeEC2InstanceConnectEndpoint = "aws:ec2:instance-connect-endpoint"
	// EC2 — networking (ec2_networking_scanners.go)
	TypeEC2VPC                  = "aws:ec2:vpc"
	TypeEC2Subnet               = "aws:ec2:subnet"
	TypeEC2InternetGateway      = "aws:ec2:internet-gateway"
	TypeEC2NatGateway           = "aws:ec2:nat-gateway"
	TypeEC2RouteTable           = "aws:ec2:route-table"
	TypeEC2EIP                  = "aws:ec2:eip"
	TypeEC2NetworkInterface     = "aws:ec2:network-interface"
	TypeEC2NetworkACL           = "aws:ec2:network-acl"
	TypeEC2VPCEndpoint          = "aws:ec2:vpc-endpoint"
	TypeEC2VPCPeeringConnection = "aws:ec2:vpc-peering-connection"
	TypeEC2DHCPOptions          = "aws:ec2:dhcp-options"
	TypeEC2EgressOnlyIGW        = "aws:ec2:egress-only-internet-gateway"
	// EC2 — VPN (ec2_vpn_scanners.go)
	TypeEC2CustomerGateway          = "aws:ec2:customer-gateway"
	TypeEC2VPNGateway               = "aws:ec2:vpn-gateway"
	TypeEC2VPNConnection            = "aws:ec2:vpn-connection"
	TypeEC2TransitGateway           = "aws:ec2:transit-gateway"
	TypeEC2TransitGatewayAttachment = "aws:ec2:transit-gateway-attachment"
	// EC2 — observability (ec2_observability_scanners.go)
	TypeEC2FlowLog                            = "aws:ec2:flow-log"
	TypeEC2PrefixList                         = "aws:ec2:prefix-list"
	TypeEC2NetworkInsightsPath                = "aws:ec2:network-insights-path"
	TypeEC2NetworkInsightsAnalysis            = "aws:ec2:network-insights-analysis"
	TypeEC2NetworkInsightsAccessScope         = "aws:ec2:network-insights-access-scope"
	TypeEC2NetworkInsightsAccessScopeAnalysis = "aws:ec2:network-insights-access-scope-analysis"
	// EC2 — IPAM (ec2_ipam_scanners.go)
	TypeEC2IPAM                             = "aws:ec2:ipam"
	TypeEC2IPAMScope                        = "aws:ec2:ipam-scope"
	TypeEC2IPAMPool                         = "aws:ec2:ipam-pool"
	TypeEC2IPAMPoolCIDR                     = "aws:ec2:ipam-pool-cidr"
	TypeEC2IPAMAllocation                   = "aws:ec2:ipam-allocation"
	TypeEC2IPAMResourceDiscovery            = "aws:ec2:ipam-resource-discovery"
	TypeEC2IPAMResourceDiscoveryAssociation = "aws:ec2:ipam-resource-discovery-association"
	// EC2 — Transit Gateway extended (ec2_tgw_ext_scanners.go)
	TypeEC2TransitGatewayConnect                    = "aws:ec2:transit-gateway-connect"
	TypeEC2TransitGatewayConnectPeer                = "aws:ec2:transit-gateway-connect-peer"
	TypeEC2TransitGatewayMulticastDomain            = "aws:ec2:transit-gateway-multicast-domain"
	TypeEC2TransitGatewayMulticastDomainAssociation = "aws:ec2:transit-gateway-multicast-domain-association"
	TypeEC2TransitGatewayMulticastGroupMember       = "aws:ec2:transit-gateway-multicast-group-member"
	TypeEC2TransitGatewayMulticastGroupSource       = "aws:ec2:transit-gateway-multicast-group-source"
	TypeEC2TransitGatewayPeeringAttachment          = "aws:ec2:transit-gateway-peering-attachment"
	TypeEC2TransitGatewayRouteTable                 = "aws:ec2:transit-gateway-route-table"
	TypeEC2TransitGatewayRouteTableAssociation      = "aws:ec2:transit-gateway-route-table-association"
	TypeEC2TransitGatewayRouteTablePropagation      = "aws:ec2:transit-gateway-route-table-propagation"
	TypeEC2TransitGatewayVPCAttachment              = "aws:ec2:transit-gateway-vpc-attachment"
	TypeEC2TransitGatewayRoute                      = "aws:ec2:transit-gateway-route"
	// EC2 — Traffic Mirroring (ec2_traffic_mirror_scanners.go)
	TypeEC2TrafficMirrorFilter     = "aws:ec2:traffic-mirror-filter"
	TypeEC2TrafficMirrorFilterRule = "aws:ec2:traffic-mirror-filter-rule"
	TypeEC2TrafficMirrorSession    = "aws:ec2:traffic-mirror-session"
	TypeEC2TrafficMirrorTarget     = "aws:ec2:traffic-mirror-target"
	// EC2 — Verified Access (ec2_verified_access_scanners.go)
	TypeEC2VerifiedAccessInstance      = "aws:ec2:verified-access-instance"
	TypeEC2VerifiedAccessTrustProvider = "aws:ec2:verified-access-trust-provider"
	TypeEC2VerifiedAccessGroup         = "aws:ec2:verified-access-group"
	TypeEC2VerifiedAccessEndpoint      = "aws:ec2:verified-access-endpoint"
	// EC2 — Local Gateway (ec2_local_gateway_scanners.go)
	TypeEC2LocalGatewayRouteTable               = "aws:ec2:local-gateway-route-table"
	TypeEC2LocalGatewayRoute                    = "aws:ec2:local-gateway-route"
	TypeEC2LocalGatewayVirtualInterface         = "aws:ec2:local-gateway-virtual-interface"
	TypeEC2LocalGatewayVirtualInterfaceGroup    = "aws:ec2:local-gateway-virtual-interface-group"
	TypeEC2LocalGatewayRouteTableVPCAssociation = "aws:ec2:local-gateway-route-table-vpc-association"
	TypeEC2LocalGatewayRouteTableVIGAssociation = "aws:ec2:local-gateway-route-table-virtual-interface-group-association"
	// EC2 — Client VPN (ec2_client_vpn_scanners.go)
	TypeEC2ClientVPNEndpoint                 = "aws:ec2:client-vpn-endpoint"
	TypeEC2ClientVPNAuthorizationRule        = "aws:ec2:client-vpn-authorization-rule"
	TypeEC2ClientVPNRoute                    = "aws:ec2:client-vpn-route"
	TypeEC2ClientVPNTargetNetworkAssociation = "aws:ec2:client-vpn-target-network-association"
	// EC2 — extended resources (ec2_compute_mgmt_scanners.go, ec2_networking_scanners.go)
	TypeEC2CapacityReservationFleet          = "aws:ec2:capacity-reservation-fleet"
	TypeEC2Fleet                             = "aws:ec2:ec2-fleet"
	TypeEC2CarrierGateway                    = "aws:ec2:carrier-gateway"
	TypeEC2VPCBlockPublicAccessOptions       = "aws:ec2:vpc-block-public-access-options"
	TypeEC2VPCBlockPublicAccessExclusion     = "aws:ec2:vpc-block-public-access-exclusion"
	TypeEC2VPCEndpointConnectionNotification = "aws:ec2:vpc-endpoint-connection-notification"
	TypeEC2VPCEndpointService                = "aws:ec2:vpc-endpoint-service"
	TypeEC2VPCEndpointServicePermissions     = "aws:ec2:vpc-endpoint-service-permissions"
	TypeEC2SecurityGroupVPCAssociation       = "aws:ec2:security-group-vpc-association"
	TypeEC2NetworkInterfacePermission        = "aws:ec2:network-interface-permission"
	TypeEC2SnapshotBlockPublicAccess         = "aws:ec2:snapshot-block-public-access"
	// EC2 — Route Server (ec2_route_server_scanners.go)
	TypeEC2RouteServer         = "aws:ec2:route-server"
	TypeEC2RouteServerEndpoint = "aws:ec2:route-server-endpoint"
	TypeEC2RouteServerPeer     = "aws:ec2:route-server-peer"
	// EC2 — IPAM Prefix List Resolver (ec2_ipam_resolver_scanners.go)
	TypeEC2IPAMPrefixListResolver       = "aws:ec2:ipam-prefix-list-resolver"
	TypeEC2IPAMPrefixListResolverTarget = "aws:ec2:ipam-prefix-list-resolver-target"
	// EC2 — Misc (ec2_misc_extra_scanners.go)
	TypeEC2CapacityManagerDataExport            = "aws:ec2:capacity-manager-data-export"
	TypeEC2NetworkPerformanceMetricSubscription = "aws:ec2:network-performance-metric-subscription"
	TypeEC2TransitGatewayMeteringPolicy         = "aws:ec2:transit-gateway-metering-policy"
	TypeEC2VPCEncryptionControl                 = "aws:ec2:vpc-encryption-control"
	TypeEC2VPNConcentrator                      = "aws:ec2:vpn-concentrator"
	// IoT — Things (iot_things_scanners.go)
	TypeIoTThing                    = "aws:iot:thing"
	TypeIoTThingGroup               = "aws:iot:thing-group"
	TypeIoTThingType                = "aws:iot:thing-type"
	TypeIoTBillingGroup             = "aws:iot:billing-group"
	TypeIoTThingPrincipalAttachment = "aws:iot:thing-principal-attachment"
	// IoT — Certs/Auth (iot_certs_scanners.go)
	TypeIoTCertificate               = "aws:iot:certificate"
	TypeIoTCACertificate             = "aws:iot:ca-certificate"
	TypeIoTCertificateProvider       = "aws:iot:certificate-provider"
	TypeIoTPolicy                    = "aws:iot:policy"
	TypeIoTPolicyPrincipalAttachment = "aws:iot:policy-principal-attachment"
	TypeIoTRoleAlias                 = "aws:iot:role-alias"
	TypeIoTAuthorizer                = "aws:iot:authorizer"
	TypeIoTDomainConfiguration       = "aws:iot:domain-configuration"
	// IoT — Defender (iot_defender_scanners.go)
	TypeIoTAccountAuditConfiguration = "aws:iot:account-audit-configuration"
	TypeIoTScheduledAudit            = "aws:iot:scheduled-audit"
	TypeIoTMitigationAction          = "aws:iot:mitigation-action"
	TypeIoTSecurityProfile           = "aws:iot:security-profile"
	TypeIoTCustomMetric              = "aws:iot:custom-metric"
	TypeIoTDimension                 = "aws:iot:dimension"
	// IoT — Jobs (iot_jobs_scanners.go)
	TypeIoTCommand              = "aws:iot:command"
	TypeIoTJobTemplate          = "aws:iot:job-template"
	TypeIoTFleetMetric          = "aws:iot:fleet-metric"
	TypeIoTProvisioningTemplate = "aws:iot:provisioning-template"
	// IoT — Software (iot_software_scanners.go)
	TypeIoTSoftwarePackage        = "aws:iot:software-package"
	TypeIoTSoftwarePackageVersion = "aws:iot:software-package-version"
	// IoT — Topic Rules (iot_topic_scanners.go)
	TypeIoTTopicRule            = "aws:iot:topic-rule"
	TypeIoTTopicRuleDestination = "aws:iot:topic-rule-destination"
	// IoT — Logging/Encryption (iot_logging_scanners.go)
	TypeIoTLogging                 = "aws:iot:logging"
	TypeIoTResourceSpecificLogging = "aws:iot:resource-specific-logging"
	TypeIoTEncryptionConfiguration = "aws:iot:encryption-configuration"
	// IAM — principals
	TypeIAMRole              = "aws:iam:role"
	TypeIAMUser              = "aws:iam:user"
	TypeIAMGroup             = "aws:iam:group"
	TypeIAMServiceLinkedRole = "aws:iam:service-linked-role"
	// IAM — policies and credentials
	TypeIAMPolicy      = "aws:iam:policy"
	TypeIAMRolePolicy  = "aws:iam:role-policy"
	TypeIAMUserPolicy  = "aws:iam:user-policy"
	TypeIAMGroupPolicy = "aws:iam:group-policy"
	TypeIAMAccessKey   = "aws:iam:access-key"
	// IAM — identity provider and certificate resources
	TypeIAMInstanceProfile   = "aws:iam:instance-profile"
	TypeIAMOIDCProvider      = "aws:iam:oidc-provider"
	TypeIAMSAMLProvider      = "aws:iam:saml-provider"
	TypeIAMServerCertificate = "aws:iam:server-certificate"
	TypeIAMVirtualMFADevice  = "aws:iam:virtual-mfa-device"
	// IAM — synthetic stub for cross-account trust principals (R5).
	// One row per foreign account ID referenced by an IAM role trust policy. NativeID = arn:aws:iam::<acct>:root.
	TypeIAMForeignAccount = "aws:iam:foreign-account"
	// Lambda
	TypeLambdaFunction          = "aws:lambda:function"
	TypeLambdaAlias             = "aws:lambda:alias"
	TypeLambdaCapacityProvider  = "aws:lambda:capacity-provider"
	TypeLambdaCodeSigningConfig = "aws:lambda:code-signing-config"
	TypeLambdaEventInvokeConfig = "aws:lambda:event-invoke-config"
	TypeLambdaESM               = "aws:lambda:event-source-mapping"
	TypeLambdaLayerVersion      = "aws:lambda:layer-version"
	TypeLambdaURL               = "aws:lambda:url"
	TypeLambdaVersion           = "aws:lambda:version"
	// RDS
	TypeRDSCustomDBEngineVersion   = "aws:rds:custom-db-engine-version"
	TypeRDSDBCluster               = "aws:rds:db-cluster"
	TypeRDSDBClusterParameterGroup = "aws:rds:db-cluster-parameter-group"
	TypeRDSDBInstance              = "aws:rds:db-instance"
	TypeRDSDBParameterGroup        = "aws:rds:db-parameter-group"
	TypeRDSDBProxy                 = "aws:rds:db-proxy"
	TypeRDSDBProxyEndpoint         = "aws:rds:db-proxy-endpoint"
	TypeRDSDBProxyTargetGroup      = "aws:rds:db-proxy-target-group"
	TypeRDSDBSecurityGroup         = "aws:rds:db-security-group"
	TypeRDSDBShardGroup            = "aws:rds:db-shard-group"
	TypeRDSDBSubnetGroup           = "aws:rds:db-subnet-group"
	TypeRDSEventSubscription       = "aws:rds:event-subscription"
	TypeRDSGlobalCluster           = "aws:rds:global-cluster"
	TypeRDSIntegration             = "aws:rds:integration"
	TypeRDSOptionGroup             = "aws:rds:option-group"
	// DynamoDB
	TypeDynamoDBTable       = "aws:dynamodb:table"
	TypeDynamoDBGlobalTable = "aws:dynamodb:global-table"
	TypeDynamoDBStream      = "aws:dynamodb:stream"
	// EFS (efs_scanners.go, efs_resolvers.go)
	TypeEFSFileSystem  = "aws:efs:file-system"
	TypeEFSMountTarget = "aws:efs:mount-target"
	TypeEFSAccessPoint = "aws:efs:access-point"
	// WAFv2 (wafv2_scanners.go, wafv2_resolvers.go)
	TypeWAFv2WebACL    = "aws:wafv2:web-acl"
	TypeWAFv2RuleGroup = "aws:wafv2:rule-group"
	TypeWAFv2IPSet     = "aws:wafv2:ip-set"
	// Network Firewall (networkfirewall_scanners.go, networkfirewall_resolvers.go)
	TypeNetworkFirewallFirewall       = "aws:network-firewall:firewall"
	TypeNetworkFirewallFirewallPolicy = "aws:network-firewall:firewall-policy"
	TypeNetworkFirewallRuleGroup      = "aws:network-firewall:rule-group"
	// EventBridge (eventbridge_scanners.go, eventbridge_resolvers.go)
	TypeEventsEventBus       = "aws:events:event-bus"
	TypeEventsRule           = "aws:events:rule"
	TypeEventsAPIDestination = "aws:events:api-destination"
	TypeEventsConnection     = "aws:events:connection"
	// CloudTrail (cloudtrail_scanners.go, cloudtrail_resolvers.go)
	TypeCloudTrailTrail          = "aws:cloudtrail:trail"
	TypeCloudTrailEventDataStore = "aws:cloudtrail:event-data-store"
	// StepFunctions (sfn_scanners.go, sfn_resolvers.go)
	TypeSFNStateMachine = "aws:sfn:state-machine"
	TypeSFNActivity     = "aws:sfn:activity"
	// Cognito (cognito_scanners.go, cognito_resolvers.go)
	TypeCognitoUserPool     = "aws:cognito:user-pool"
	TypeCognitoIdentityPool = "aws:cognito:identity-pool"
	TypeCognitoAppClient    = "aws:cognito:app-client"
	// Cognito — extended (cognito_extended_scanners.go)
	TypeCognitoUserPoolDomain                      = "aws:cognito:user-pool-domain"
	TypeCognitoUserPoolGroup                       = "aws:cognito:user-pool-group"
	TypeCognitoUserPoolIdentityProvider            = "aws:cognito:user-pool-identity-provider"
	TypeCognitoUserPoolResourceServer              = "aws:cognito:user-pool-resource-server"
	TypeCognitoUserPoolRiskConfigurationAttachment = "aws:cognito:user-pool-risk-configuration-attachment"
	TypeCognitoUserPoolUICustomizationAttachment   = "aws:cognito:user-pool-ui-customization-attachment"
	TypeCognitoLogDeliveryConfiguration            = "aws:cognito:log-delivery-configuration"
	TypeCognitoTerms                               = "aws:cognito:terms"
	TypeCognitoIdentityPoolRoleAttachment          = "aws:cognito:identity-pool-role-attachment"
	// AppStream (appstream_scanners.go)
	TypeAppStreamAppBlock                          = "aws:appstream:app-block"
	TypeAppStreamAppBlockBuilder                   = "aws:appstream:app-block-builder"
	TypeAppStreamApplication                       = "aws:appstream:application"
	TypeAppStreamApplicationEntitlementAssociation = "aws:appstream:application-entitlement-association"
	TypeAppStreamApplicationFleetAssociation       = "aws:appstream:application-fleet-association"
	TypeAppStreamDirectoryConfig                   = "aws:appstream:directory-config"
	TypeAppStreamEntitlement                       = "aws:appstream:entitlement"
	TypeAppStreamFleet                             = "aws:appstream:fleet"
	TypeAppStreamImageBuilder                      = "aws:appstream:image-builder"
	TypeAppStreamStack                             = "aws:appstream:stack"
	TypeAppStreamStackFleetAssociation             = "aws:appstream:stack-fleet-association"
	TypeAppStreamStackUserAssociation              = "aws:appstream:stack-user-association"
	TypeAppStreamUser                              = "aws:appstream:user"
	// Wisdom (Amazon Q Connect — qconnect SDK) (wisdom_scanners.go)
	TypeWisdomAssistant              = "aws:wisdom:assistant"
	TypeWisdomAssistantAssociation   = "aws:wisdom:assistant-association"
	TypeWisdomAIAgent                = "aws:wisdom:ai-agent"
	TypeWisdomAIAgentVersion         = "aws:wisdom:ai-agent-version"
	TypeWisdomAIGuardrail            = "aws:wisdom:ai-guardrail"
	TypeWisdomAIGuardrailVersion     = "aws:wisdom:ai-guardrail-version"
	TypeWisdomAIPrompt               = "aws:wisdom:ai-prompt"
	TypeWisdomAIPromptVersion        = "aws:wisdom:ai-prompt-version"
	TypeWisdomKnowledgeBase          = "aws:wisdom:knowledge-base"
	TypeWisdomMessageTemplate        = "aws:wisdom:message-template"
	TypeWisdomMessageTemplateVersion = "aws:wisdom:message-template-version"
	TypeWisdomQuickResponse          = "aws:wisdom:quick-response"
	// EKS
	TypeEKSCluster                = "aws:eks:cluster"
	TypeEKSAccessEntry            = "aws:eks:access-entry"
	TypeEKSAddon                  = "aws:eks:addon"
	TypeEKSCapability             = "aws:eks:capability"
	TypeEKSFargateProfile         = "aws:eks:fargate-profile"
	TypeEKSIdentityProviderConfig = "aws:eks:identity-provider-config"
	TypeEKSNodegroup              = "aws:eks:nodegroup"
	TypeEKSPodIdentityAssociation = "aws:eks:pod-identity-association"
	// Classic ELB (elb_classic_scanners.go, elb_classic_resolvers.go)
	TypeELBClassicLoadBalancer = "aws:elasticloadbalancing:load-balancer"
	// ELBv2 (elb_scanners.go, elb_resolvers.go)
	TypeELBv2LoadBalancer         = "aws:elasticloadbalancingv2:load-balancer"
	TypeELBv2Listener             = "aws:elasticloadbalancingv2:listener"
	TypeELBv2ListenerCertificate  = "aws:elasticloadbalancingv2:listener-certificate"
	TypeELBv2ListenerRule         = "aws:elasticloadbalancingv2:listener-rule"
	TypeELBv2TargetGroup          = "aws:elasticloadbalancingv2:target-group"
	TypeELBv2TrustStore           = "aws:elasticloadbalancingv2:trust-store"
	TypeELBv2TrustStoreRevocation = "aws:elasticloadbalancingv2:trust-store-revocation"
	// S3 — buckets (s3_scanners.go)
	TypeS3Bucket = "aws:s3:bucket"
	// S3 — extended (s3_scanners.go, s3control_scanners.go)
	TypeS3BucketPolicy                 = "aws:s3:bucket-policy"
	TypeS3AccessGrantsInstance         = "aws:s3:access-grants-instance"
	TypeS3AccessGrantsLocation         = "aws:s3:access-grants-location"
	TypeS3AccessGrant                  = "aws:s3:access-grant"
	TypeS3AccessPoint                  = "aws:s3:access-point"
	TypeS3MultiRegionAccessPoint       = "aws:s3:multi-region-access-point"
	TypeS3MultiRegionAccessPointPolicy = "aws:s3:multi-region-access-point-policy"
	TypeS3StorageLens                  = "aws:s3:storage-lens"
	TypeS3StorageLensGroup             = "aws:s3:storage-lens-group"
	// SNS
	TypeSNSTopic = "aws:sns:topic"
	// SQS
	TypeSQSQueue = "aws:sqs:queue"
	// ECS
	TypeECSCluster                             = "aws:ecs:cluster"
	TypeECSService                             = "aws:ecs:service"
	TypeECSTaskDefinition                      = "aws:ecs:task-definition"
	TypeECSCapacityProvider                    = "aws:ecs:capacity-provider"
	TypeECSClusterCapacityProviderAssociations = "aws:ecs:cluster-capacity-provider-associations"
	TypeECSTaskSet                             = "aws:ecs:task-set"
	// ECR
	TypeECRRepository                 = "aws:ecr:repository"
	TypeECRPublicRepository           = "aws:ecr:public-repository"
	TypeECRPullThroughCacheRule       = "aws:ecr:pull-through-cache-rule"
	TypeECRPullTimeUpdateExclusion    = "aws:ecr:pull-time-update-exclusion"
	TypeECRRegistryPolicy             = "aws:ecr:registry-policy"
	TypeECRRegistryScanningConfig     = "aws:ecr:registry-scanning-configuration"
	TypeECRReplicationConfiguration   = "aws:ecr:replication-configuration"
	TypeECRRepositoryCreationTemplate = "aws:ecr:repository-creation-template"
	TypeECRSigningConfiguration       = "aws:ecr:signing-configuration"
	// ElastiCache
	TypeElastiCacheReplicationGroup       = "aws:elasticache:replication-group"
	TypeElastiCacheCacheCluster           = "aws:elasticache:cache-cluster"
	TypeElastiCacheGlobalReplicationGroup = "aws:elasticache:global-replication-group"
	TypeElastiCacheParameterGroup         = "aws:elasticache:parameter-group"
	TypeElastiCacheSecurityGroup          = "aws:elasticache:security-group"
	TypeElastiCacheServerlessCache        = "aws:elasticache:serverless-cache"
	TypeElastiCacheSubnetGroup            = "aws:elasticache:subnet-group"
	TypeElastiCacheUser                   = "aws:elasticache:user"
	TypeElastiCacheUserGroup              = "aws:elasticache:user-group"
	// CloudFront
	TypeCloudFrontDistribution               = "aws:cloudfront:distribution"
	TypeCloudFrontAnycastIPList              = "aws:cloudfront:anycast-ip-list"
	TypeCloudFrontCachePolicy                = "aws:cloudfront:cache-policy"
	TypeCloudFrontOAI                        = "aws:cloudfront:cloud-front-origin-access-identity"
	TypeCloudFrontConnectionFunction         = "aws:cloudfront:connection-function"
	TypeCloudFrontConnectionGroup            = "aws:cloudfront:connection-group"
	TypeCloudFrontContinuousDeploymentPolicy = "aws:cloudfront:continuous-deployment-policy"
	TypeCloudFrontDistributionTenant         = "aws:cloudfront:distribution-tenant"
	TypeCloudFrontFunction                   = "aws:cloudfront:function"
	TypeCloudFrontKeyGroup                   = "aws:cloudfront:key-group"
	TypeCloudFrontKeyValueStore              = "aws:cloudfront:key-value-store"
	TypeCloudFrontMonitoringSubscription     = "aws:cloudfront:monitoring-subscription"
	TypeCloudFrontOriginAccessControl        = "aws:cloudfront:origin-access-control"
	TypeCloudFrontOriginRequestPolicy        = "aws:cloudfront:origin-request-policy"
	TypeCloudFrontPublicKey                  = "aws:cloudfront:public-key"
	TypeCloudFrontRealtimeLogConfig          = "aws:cloudfront:realtime-log-config"
	TypeCloudFrontResponseHeadersPolicy      = "aws:cloudfront:response-headers-policy"
	TypeCloudFrontStreamingDistribution      = "aws:cloudfront:streaming-distribution"
	TypeCloudFrontTrustStore                 = "aws:cloudfront:trust-store"
	TypeCloudFrontVpcOrigin                  = "aws:cloudfront:vpc-origin"
	// Route53
	TypeRoute53HostedZone     = "aws:route53:hosted-zone"
	TypeRoute53RecordSet      = "aws:route53:record-set"
	TypeRoute53CIDRCollection = "aws:route53:cidr-collection"
	TypeRoute53DNSSEC         = "aws:route53:dnssec"
	TypeRoute53HealthCheck    = "aws:route53:health-check"
	TypeRoute53KeySigningKey  = "aws:route53:key-signing-key"
	// API Gateway v1 (apigateway_scanners.go, apigateway_resolvers.go)
	TypeAPIGatewayRestAPI               = "aws:apigateway:rest-api"
	TypeAPIGatewayAccount               = "aws:apigateway:account"
	TypeAPIGatewayAPIKey                = "aws:apigateway:api-key"
	TypeAPIGatewayAuthorizer            = "aws:apigateway:authorizer"
	TypeAPIGatewayBasePathMapping       = "aws:apigateway:base-path-mapping"
	TypeAPIGatewayClientCertificate     = "aws:apigateway:client-certificate"
	TypeAPIGatewayDeployment            = "aws:apigateway:deployment"
	TypeAPIGatewayDocumentationPart     = "aws:apigateway:documentation-part"
	TypeAPIGatewayDocumentationVersion  = "aws:apigateway:documentation-version"
	TypeAPIGatewayDomainName            = "aws:apigateway:domain-name"
	TypeAPIGatewayDomainNameAccessAssoc = "aws:apigateway:domain-name-access-association"
	TypeAPIGatewayGatewayResponse       = "aws:apigateway:gateway-response"
	TypeAPIGatewayMethod                = "aws:apigateway:method"
	TypeAPIGatewayModel                 = "aws:apigateway:model"
	TypeAPIGatewayRequestValidator      = "aws:apigateway:request-validator"
	TypeAPIGatewayResource              = "aws:apigateway:resource"
	TypeAPIGatewayStage                 = "aws:apigateway:stage"
	TypeAPIGatewayUsagePlan             = "aws:apigateway:usage-plan"
	TypeAPIGatewayUsagePlanKey          = "aws:apigateway:usage-plan-key"
	TypeAPIGatewayVpcLink               = "aws:apigateway:vpc-link"
	// API Gateway v2 (apigateway_scanners.go)
	TypeAPIGatewayV2API                  = "aws:apigatewayv2:api"
	TypeAPIGatewayV2Authorizer           = "aws:apigatewayv2:authorizer"
	TypeAPIGatewayBasePathMappingV2      = "aws:apigatewayv2:base-path-mapping"
	TypeAPIGatewayDomainNameV2           = "aws:apigatewayv2:domain-name"
	TypeAPIGatewayV2Deployment           = "aws:apigatewayv2:deployment"
	TypeAPIGatewayV2Integration          = "aws:apigatewayv2:integration"
	TypeAPIGatewayV2IntegrationResponse  = "aws:apigatewayv2:integration-response"
	TypeAPIGatewayV2Model                = "aws:apigatewayv2:model"
	TypeAPIGatewayV2Route                = "aws:apigatewayv2:route"
	TypeAPIGatewayV2RouteResponse        = "aws:apigatewayv2:route-response"
	TypeAPIGatewayV2Stage                = "aws:apigatewayv2:stage"
	TypeAPIGatewayV2RoutingRule          = "aws:apigatewayv2:routing-rule"
	TypeAPIGatewayPrivateDomainName      = "aws:apigateway:domain-name-v2"
	TypeAPIGatewayPrivateBasePathMapping = "aws:apigateway:base-path-mapping-v2"
	// CloudWatch (cloudwatch_scanners.go)
	TypeCloudWatchAlarm           = "aws:cloudwatch:alarm"
	TypeCloudWatchAlarmMuteRule   = "aws:cloudwatch:alarm-mute-rule"
	TypeCloudWatchAnomalyDetector = "aws:cloudwatch:anomaly-detector"
	TypeCloudWatchCompositeAlarm  = "aws:cloudwatch:composite-alarm"
	TypeCloudWatchDashboard       = "aws:cloudwatch:dashboard"
	TypeCloudWatchInsightRule     = "aws:cloudwatch:insight-rule"
	TypeCloudWatchMetricStream    = "aws:cloudwatch:metric-stream"
	// CloudWatch Logs (logs_scanners.go)
	TypeLogsAccountPolicy      = "aws:logs:account-policy"
	TypeLogsDelivery           = "aws:logs:delivery"
	TypeLogsDeliveryDest       = "aws:logs:delivery-destination"
	TypeLogsDeliverySource     = "aws:logs:delivery-source"
	TypeLogsDestination        = "aws:logs:destination"
	TypeLogsIntegration        = "aws:logs:integration"
	TypeLogsLogAnomalyDetector = "aws:logs:log-anomaly-detector"
	TypeLogsLogGroup           = "aws:logs:log-group"
	TypeLogsLogStream          = "aws:logs:log-stream"
	TypeLogsMetricFilter       = "aws:logs:metric-filter"
	TypeLogsQueryDefinition    = "aws:logs:query-definition"
	TypeLogsResourcePolicy     = "aws:logs:resource-policy"
	TypeLogsScheduledQuery     = "aws:logs:scheduled-query"
	TypeLogsSubscriptionFilter = "aws:logs:subscription-filter"
	TypeLogsTransformer        = "aws:logs:transformer"

	// KMS (kms_scanners.go)
	TypeKMSKey   = "aws:kms:key"
	TypeKMSAlias = "aws:kms:alias"
	TypeKMSGrant = "aws:kms:grant"
	// MSK / Kafka (kafka_scanners.go)
	TypeMSKCluster          = "aws:kafka:cluster"
	TypeMSKBatchScramSecret = "aws:kafka:batch-scram-secret"
	TypeMSKClusterPolicy    = "aws:kafka:cluster-policy"
	TypeMSKConfiguration    = "aws:kafka:configuration"
	TypeMSKReplicator       = "aws:kafka:replicator"
	TypeMSKVpcConnection    = "aws:kafka:vpc-connection"
	// Secrets Manager (secretsmanager_scanners.go)
	TypeSecretsManagerSecret = "aws:secretsmanager:secret"
	// Organizations (organizations_scanners.go)
	TypeOrganization         = "aws:organizations:organization"
	TypeOrganizationsAccount = "aws:organizations:account"
	TypeOrganizationsOU      = "aws:organizations:ou"
	TypeOrganizationsSCP     = "aws:organizations:scp"
	// ACM (acm_scanners.go)
	TypeACMCertificate = "aws:acm:certificate"
	TypeACMPrivateCA   = "aws:acm:private-ca"
	// Kinesis Data Streams (kinesis_scanners.go)
	TypeKinesisStream = "aws:kinesis:stream"
	// Firehose (firehose_scanners.go)
	TypeFirehoseDeliveryStream = "aws:firehose:delivery-stream"
	// SSM (ssm_scanners.go)
	TypeSSMParameter               = "aws:ssm:parameter"
	TypeSSMDocument                = "aws:ssm:document"
	TypeSSMPatchBaseline           = "aws:ssm:patch-baseline"
	TypeSSMAssociation             = "aws:ssm:association"
	TypeSSMMaintenanceWindow       = "aws:ssm:maintenance-window"
	TypeSSMMaintenanceWindowTarget = "aws:ssm:maintenance-window-target"
	TypeSSMMaintenanceWindowTask   = "aws:ssm:maintenance-window-task"
	TypeSSMResourceDataSync        = "aws:ssm:resource-data-sync"
	// GuardDuty (guardduty_scanners.go)
	TypeGuardDutyDetector              = "aws:guardduty:detector"
	TypeGuardDutyFilter                = "aws:guardduty:filter"
	TypeGuardDutyIPSet                 = "aws:guardduty:ipset"
	TypeGuardDutyMember                = "aws:guardduty:member"
	TypeGuardDutyMalwareProtectionPlan = "aws:guardduty:malware-protection-plan"
	TypeGuardDutyPublishingDestination = "aws:guardduty:publishing-destination"
	TypeGuardDutyThreatEntitySet       = "aws:guardduty:threat-entity-set"
	TypeGuardDutyThreatIntelSet        = "aws:guardduty:threat-intel-set"
	TypeGuardDutyTrustedEntitySet      = "aws:guardduty:trusted-entity-set"
	// Config (config_scanners.go)
	TypeConfigRecorder                    = "aws:config:recorder"
	TypeConfigDeliveryChannel             = "aws:config:delivery-channel"
	TypeConfigRule                        = "aws:config:rule"
	TypeConfigAggregationAuthorization    = "aws:config:aggregation-authorization"
	TypeConfigConfigurationAggregator     = "aws:config:configuration-aggregator"
	TypeConfigConformancePack             = "aws:config:conformance-pack"
	TypeConfigOrganizationConfigRule      = "aws:config:organization-config-rule"
	TypeConfigOrganizationConformancePack = "aws:config:organization-conformance-pack"
	TypeConfigRemediationConfiguration    = "aws:config:remediation-configuration"
	TypeConfigStoredQuery                 = "aws:config:stored-query"
	// Backup (backup_scanners.go)
	TypeBackupVault                   = "aws:backup:vault"
	TypeBackupLogicallyAirGappedVault = "aws:backup:logically-air-gapped-vault"
	TypeBackupPlan                    = "aws:backup:plan"
	TypeBackupSelection               = "aws:backup:selection"
	// Backup Gateway (backupgateway_scanners.go)
	TypeBackupGatewayHypervisor = "aws:backupgateway:hypervisor"
	// BCM Data Exports (bcmdataexports_scanners.go)
	TypeBCMDataExportsExport = "aws:bcmdataexports:export"
	// BCM Pricing Calculator (bcmpricingcalculator_scanners.go)
	TypeBcmPricingCalculatorBillScenario = "aws:bcmpricingcalculator:bill-scenario"
	// Billing (billing_scanners.go, billing_resolvers.go)
	TypeBillingView = "aws:billing:billing-view"
	// Billing Conductor (billingconductor_scanners.go, billingconductor_resolvers.go)
	TypeBillingConductorBillingGroup   = "aws:billingconductor:billing-group"
	TypeBillingConductorCustomLineItem = "aws:billingconductor:custom-line-item"
	TypeBillingConductorPricingPlan    = "aws:billingconductor:pricing-plan"
	TypeBillingConductorPricingRule    = "aws:billingconductor:pricing-rule"
	// Braket (braket_scanners.go, braket_resolvers.go)
	TypeBraketSpendingLimit = "aws:braket:spending-limit"
	// CloudFormation (cloudformation_scanners.go, cloudformation_resolvers.go)
	TypeCloudFormationStack    = "aws:cloudformation:stack"
	TypeCloudFormationStackSet = "aws:cloudformation:stack-set"
	// IAM Identity Center / Identity Store (sso_scanners.go, sso_resolvers.go)
	TypeSSOInstance          = "aws:sso:instance"
	TypeSSOPermissionSet     = "aws:sso:permission-set"
	TypeSSOAccountAssignment = "aws:sso:account-assignment"
	TypeIdentityStoreUser    = "aws:identitystore:user"
	TypeIdentityStoreGroup   = "aws:identitystore:group"
	// Macie (macie_scanners.go, macie_resolvers.go)
	TypeMacieSession              = "aws:macie:session"
	TypeMacieClassificationJob    = "aws:macie:classification-job"
	TypeMacieCustomDataIdentifier = "aws:macie:custom-data-identifier"
	TypeMacieAllowList            = "aws:macie:allow-list"
	// SageMaker — Studio (sagemaker_scanners.go)
	TypeSageMakerDomain                = "aws:sagemaker:domain"
	TypeSageMakerUserProfile           = "aws:sagemaker:user-profile"
	TypeSageMakerSpace                 = "aws:sagemaker:space"
	TypeSageMakerApp                   = "aws:sagemaker:app"
	TypeSageMakerAppImageConfig        = "aws:sagemaker:app-image-config"
	TypeSageMakerStudioLifecycleConfig = "aws:sagemaker:studio-lifecycle-config"
	// SageMaker — Training/Notebook (sagemaker_training_scanners.go)
	TypeSageMakerNotebookInstance                = "aws:sagemaker:notebook-instance"
	TypeSageMakerNotebookInstanceLifecycleConfig = "aws:sagemaker:notebook-instance-lifecycle-config"
	TypeSageMakerCodeRepository                  = "aws:sagemaker:code-repository"
	TypeSageMakerProcessingJob                   = "aws:sagemaker:processing-job"
	// SageMaker — Inference (sagemaker_inference_scanners.go)
	TypeSageMakerEndpoint            = "aws:sagemaker:endpoint"
	TypeSageMakerEndpointConfig      = "aws:sagemaker:endpoint-config"
	TypeSageMakerModel               = "aws:sagemaker:model"
	TypeSageMakerInferenceComponent  = "aws:sagemaker:inference-component"
	TypeSageMakerInferenceExperiment = "aws:sagemaker:inference-experiment"
	// SageMaker — Model registry (sagemaker_registry_scanners.go)
	TypeSageMakerModelPackage         = "aws:sagemaker:model-package"
	TypeSageMakerModelPackageGroup    = "aws:sagemaker:model-package-group"
	TypeSageMakerModelCard            = "aws:sagemaker:model-card"
	TypeSageMakerFeatureGroup         = "aws:sagemaker:feature-group"
	TypeSageMakerMlflowTrackingServer = "aws:sagemaker:mlflow-tracking-server"
	// SageMaker — Monitoring (sagemaker_monitoring_scanners.go)
	TypeSageMakerMonitoringSchedule               = "aws:sagemaker:monitoring-schedule"
	TypeSageMakerDataQualityJobDefinition         = "aws:sagemaker:data-quality-job-definition"
	TypeSageMakerModelBiasJobDefinition           = "aws:sagemaker:model-bias-job-definition"
	TypeSageMakerModelExplainabilityJobDefinition = "aws:sagemaker:model-explainability-job-definition"
	TypeSageMakerModelQualityJobDefinition        = "aws:sagemaker:model-quality-job-definition"
	// SageMaker — Pipelines (sagemaker_pipelines_scanners.go)
	TypeSageMakerPipeline   = "aws:sagemaker:pipeline"
	TypeSageMakerProject    = "aws:sagemaker:project"
	TypeSageMakerPartnerApp = "aws:sagemaker:partner-app"
	// SageMaker — Edge / images (sagemaker_edge_scanners.go)
	TypeSageMakerDeviceFleet  = "aws:sagemaker:device-fleet"
	TypeSageMakerDevice       = "aws:sagemaker:device"
	TypeSageMakerImage        = "aws:sagemaker:image"
	TypeSageMakerImageVersion = "aws:sagemaker:image-version"
	// SageMaker — Misc (sagemaker_misc_scanners.go)
	TypeSageMakerCluster  = "aws:sagemaker:cluster"
	TypeSageMakerWorkteam = "aws:sagemaker:workteam"
	// Connect — Core (connect_core_scanners.go)
	TypeConnectInstance                 = "aws:connect:instance"
	TypeConnectTrafficDistributionGroup = "aws:connect:traffic-distribution-group"
	TypeConnectPhoneNumber              = "aws:connect:phone-number"
	TypeConnectEmailAddress             = "aws:connect:email-address"
	// Connect — Routing (connect_routing_scanners.go)
	TypeConnectQueue            = "aws:connect:queue"
	TypeConnectRoutingProfile   = "aws:connect:routing-profile"
	TypeConnectHoursOfOperation = "aws:connect:hours-of-operation"
	TypeConnectAgentStatus      = "aws:connect:agent-status"
	TypeConnectQuickConnect     = "aws:connect:quick-connect"
	// Connect — Users (connect_users_scanners.go)
	TypeConnectUser                   = "aws:connect:user"
	TypeConnectUserHierarchyGroup     = "aws:connect:user-hierarchy-group"
	TypeConnectUserHierarchyStructure = "aws:connect:user-hierarchy-structure"
	TypeConnectSecurityProfile        = "aws:connect:security-profile"
	TypeConnectPredefinedAttribute    = "aws:connect:predefined-attribute"
	// Connect — Flows (connect_flows_scanners.go)
	TypeConnectContactFlow              = "aws:connect:contact-flow"
	TypeConnectContactFlowVersion       = "aws:connect:contact-flow-version"
	TypeConnectContactFlowModule        = "aws:connect:contact-flow-module"
	TypeConnectContactFlowModuleVersion = "aws:connect:contact-flow-module-version"
	TypeConnectContactFlowModuleAlias   = "aws:connect:contact-flow-module-alias"
	// Connect — Integration (connect_integration_scanners.go)
	TypeConnectApprovedOrigin         = "aws:connect:approved-origin"
	TypeConnectSecurityKey            = "aws:connect:security-key"
	TypeConnectInstanceStorageConfig  = "aws:connect:instance-storage-config"
	TypeConnectIntegrationAssociation = "aws:connect:integration-association"
	TypeConnectNotification           = "aws:connect:notification"
	TypeConnectRule                   = "aws:connect:rule"
	// Connect — Workspace (connect_workspace_scanners.go)
	TypeConnectTaskTemplate   = "aws:connect:task-template"
	TypeConnectEvaluationForm = "aws:connect:evaluation-form"
	TypeConnectView           = "aws:connect:view"
	TypeConnectViewVersion    = "aws:connect:view-version"
	TypeConnectWorkspace      = "aws:connect:workspace"
	TypeConnectPrompt         = "aws:connect:prompt"
	// Connect — DataTable (connect_datatable_scanners.go)
	TypeConnectDataTable          = "aws:connect:data-table"
	TypeConnectDataTableAttribute = "aws:connect:data-table-attribute"
	TypeConnectDataTableRecord    = "aws:connect:data-table-record"
	// Shield Advanced (shield_scanners.go, shield_resolvers.go)
	TypeShieldProtection      = "aws:shield:protection"
	TypeShieldProtectionGroup = "aws:shield:protection-group"
	// Security Hub (securityhub_scanners.go, securityhub_resolvers.go)
	TypeSecurityHubHub                   = "aws:securityhub:hub"
	TypeSecurityHubInsight               = "aws:securityhub:insight"
	TypeSecurityHubStandardsSubscription = "aws:securityhub:standards-subscription"
	TypeSecurityHubProductSubscription   = "aws:securityhub:product-subscription"
	// SecurityHub — extended (securityhub_extended_scanners.go)
	TypeSecurityHubAggregatorV2              = "aws:securityhub:aggregator-v2"
	TypeSecurityHubAutomationRule            = "aws:securityhub:automation-rule"
	TypeSecurityHubAutomationRuleV2          = "aws:securityhub:automation-rule-v2"
	TypeSecurityHubConfigurationPolicy       = "aws:securityhub:configuration-policy"
	TypeSecurityHubConnectorV2               = "aws:securityhub:connector-v2"
	TypeSecurityHubFindingAggregator         = "aws:securityhub:finding-aggregator"
	TypeSecurityHubHubV2                     = "aws:securityhub:hub-v2"
	TypeSecurityHubOrganizationConfiguration = "aws:securityhub:organization-configuration"
	TypeSecurityHubPolicyAssociation         = "aws:securityhub:policy-association"
	TypeSecurityHubSecurityControl           = "aws:securityhub:security-control"
	TypeSecurityHubStandard                  = "aws:securityhub:standard"
	// MediaConnect (mediaconnect_scanners.go)
	TypeMediaConnectBridge                 = "aws:mediaconnect:bridge"
	TypeMediaConnectBridgeOutput           = "aws:mediaconnect:bridge-output"
	TypeMediaConnectBridgeSource           = "aws:mediaconnect:bridge-source"
	TypeMediaConnectFlow                   = "aws:mediaconnect:flow"
	TypeMediaConnectFlowEntitlement        = "aws:mediaconnect:flow-entitlement"
	TypeMediaConnectFlowOutput             = "aws:mediaconnect:flow-output"
	TypeMediaConnectFlowSource             = "aws:mediaconnect:flow-source"
	TypeMediaConnectFlowVpcInterface       = "aws:mediaconnect:flow-vpc-interface"
	TypeMediaConnectGateway                = "aws:mediaconnect:gateway"
	TypeMediaConnectRouterInput            = "aws:mediaconnect:router-input"
	TypeMediaConnectRouterNetworkInterface = "aws:mediaconnect:router-network-interface"
	TypeMediaConnectRouterOutput           = "aws:mediaconnect:router-output"
	// AppSync (appsync_scanners.go)
	TypeAppSyncApi                      = "aws:appsync:api"
	TypeAppSyncApiCache                 = "aws:appsync:api-cache"
	TypeAppSyncApiKey                   = "aws:appsync:api-key"
	TypeAppSyncChannelNamespace         = "aws:appsync:channel-namespace"
	TypeAppSyncDataSource               = "aws:appsync:data-source"
	TypeAppSyncDomainName               = "aws:appsync:domain-name"
	TypeAppSyncDomainNameApiAssociation = "aws:appsync:domain-name-api-association"
	TypeAppSyncFunctionConfiguration    = "aws:appsync:function-configuration"
	TypeAppSyncGraphQLApi               = "aws:appsync:graphql-api"
	TypeAppSyncGraphQLSchema            = "aws:appsync:graphql-schema"
	TypeAppSyncSourceApiAssociation     = "aws:appsync:source-api-association"
	// QuickSight (quicksight_scanners.go)
	TypeQuickSightActionConnector   = "aws:quicksight:action-connector"
	TypeQuickSightAnalysis          = "aws:quicksight:analysis"
	TypeQuickSightCustomPermissions = "aws:quicksight:custom-permissions"
	TypeQuickSightDashboard         = "aws:quicksight:dashboard"
	TypeQuickSightDataSet           = "aws:quicksight:data-set"
	TypeQuickSightDataSource        = "aws:quicksight:data-source"
	TypeQuickSightFolder            = "aws:quicksight:folder"
	TypeQuickSightRefreshSchedule   = "aws:quicksight:refresh-schedule"
	TypeQuickSightTemplate          = "aws:quicksight:template"
	TypeQuickSightTheme             = "aws:quicksight:theme"
	TypeQuickSightTopic             = "aws:quicksight:topic"
	TypeQuickSightVPCConnection     = "aws:quicksight:vpc-connection"
	// Route53Resolver (route53resolver_scanners.go)
	TypeRoute53ResolverFirewallDomainList                    = "aws:route53resolver:firewall-domain-list"
	TypeRoute53ResolverFirewallRuleGroup                     = "aws:route53resolver:firewall-rule-group"
	TypeRoute53ResolverFirewallRuleGroupAssociation          = "aws:route53resolver:firewall-rule-group-association"
	TypeRoute53ResolverOutpostResolver                       = "aws:route53resolver:outpost-resolver"
	TypeRoute53ResolverResolverConfig                        = "aws:route53resolver:resolver-config"
	TypeRoute53ResolverResolverDNSSECConfig                  = "aws:route53resolver:resolver-dnssec-config"
	TypeRoute53ResolverResolverEndpoint                      = "aws:route53resolver:resolver-endpoint"
	TypeRoute53ResolverResolverQueryLoggingConfig            = "aws:route53resolver:resolver-query-logging-config"
	TypeRoute53ResolverResolverQueryLoggingConfigAssociation = "aws:route53resolver:resolver-query-logging-config-association"
	TypeRoute53ResolverResolverRule                          = "aws:route53resolver:resolver-rule"
	TypeRoute53ResolverResolverRuleAssociation               = "aws:route53resolver:resolver-rule-association"
	// IoTWireless (iotwireless_scanners.go)
	TypeIoTWirelessDestination                  = "aws:iotwireless:destination"
	TypeIoTWirelessDeviceProfile                = "aws:iotwireless:device-profile"
	TypeIoTWirelessFuotaTask                    = "aws:iotwireless:fuota-task"
	TypeIoTWirelessMulticastGroup               = "aws:iotwireless:multicast-group"
	TypeIoTWirelessNetworkAnalyzerConfiguration = "aws:iotwireless:network-analyzer-configuration"
	TypeIoTWirelessPartnerAccount               = "aws:iotwireless:partner-account"
	TypeIoTWirelessServiceProfile               = "aws:iotwireless:service-profile"
	TypeIoTWirelessTaskDefinition               = "aws:iotwireless:task-definition"
	TypeIoTWirelessWirelessDevice               = "aws:iotwireless:wireless-device"
	TypeIoTWirelessWirelessDeviceImportTask     = "aws:iotwireless:wireless-device-import-task"
	TypeIoTWirelessWirelessGateway              = "aws:iotwireless:wireless-gateway"
	// GameLift (gamelift_scanners.go)
	TypeGameLiftAlias                    = "aws:gamelift:alias"
	TypeGameLiftBuild                    = "aws:gamelift:build"
	TypeGameLiftContainerFleet           = "aws:gamelift:container-fleet"
	TypeGameLiftContainerGroupDefinition = "aws:gamelift:container-group-definition"
	TypeGameLiftFleet                    = "aws:gamelift:fleet"
	TypeGameLiftGameServerGroup          = "aws:gamelift:game-server-group"
	TypeGameLiftGameSessionQueue         = "aws:gamelift:game-session-queue"
	TypeGameLiftLocation                 = "aws:gamelift:location"
	TypeGameLiftMatchmakingConfiguration = "aws:gamelift:matchmaking-configuration"
	TypeGameLiftMatchmakingRuleSet       = "aws:gamelift:matchmaking-rule-set"
	TypeGameLiftScript                   = "aws:gamelift:script"
	// DMS (dms_scanners.go)
	TypeDMSCertificate            = "aws:dms:certificate"
	TypeDMSDataMigration          = "aws:dms:data-migration"
	TypeDMSDataProvider           = "aws:dms:data-provider"
	TypeDMSEndpoint               = "aws:dms:endpoint"
	TypeDMSEventSubscription      = "aws:dms:event-subscription"
	TypeDMSInstanceProfile        = "aws:dms:instance-profile"
	TypeDMSMigrationProject       = "aws:dms:migration-project"
	TypeDMSReplicationConfig      = "aws:dms:replication-config"
	TypeDMSReplicationInstance    = "aws:dms:replication-instance"
	TypeDMSReplicationSubnetGroup = "aws:dms:replication-subnet-group"
	TypeDMSReplicationTask        = "aws:dms:replication-task"
	// Deadline (deadline_scanners.go)
	TypeDeadlineFarm                  = "aws:deadline:farm"
	TypeDeadlineFleet                 = "aws:deadline:fleet"
	TypeDeadlineLicenseEndpoint       = "aws:deadline:license-endpoint"
	TypeDeadlineLimit                 = "aws:deadline:limit"
	TypeDeadlineMeteredProduct        = "aws:deadline:metered-product"
	TypeDeadlineMonitor               = "aws:deadline:monitor"
	TypeDeadlineQueue                 = "aws:deadline:queue"
	TypeDeadlineQueueEnvironment      = "aws:deadline:queue-environment"
	TypeDeadlineQueueFleetAssociation = "aws:deadline:queue-fleet-association"
	TypeDeadlineQueueLimitAssociation = "aws:deadline:queue-limit-association"
	TypeDeadlineStorageProfile        = "aws:deadline:storage-profile"
	// WorkSpacesWeb (workspacesweb_scanners.go)
	TypeWSWBrowserSettings           = "aws:workspaces-web:browser-settings"
	TypeWSWDataProtectionSettings    = "aws:workspaces-web:data-protection-settings"
	TypeWSWIdentityProvider          = "aws:workspaces-web:identity-provider"
	TypeWSWIPAccessSettings          = "aws:workspaces-web:ip-access-settings"
	TypeWSWNetworkSettings           = "aws:workspaces-web:network-settings"
	TypeWSWPortal                    = "aws:workspaces-web:portal"
	TypeWSWSessionLogger             = "aws:workspaces-web:session-logger"
	TypeWSWTrustStore                = "aws:workspaces-web:trust-store"
	TypeWSWUserAccessLoggingSettings = "aws:workspaces-web:user-access-logging-settings"
	TypeWSWUserSettings              = "aws:workspaces-web:user-settings"
	// IVS (ivs_scanners.go)
	TypeIVSChannel                   = "aws:ivs:channel"
	TypeIVSEncoderConfiguration      = "aws:ivs:encoder-configuration"
	TypeIVSIngestConfiguration       = "aws:ivs:ingest-configuration"
	TypeIVSPlaybackKeyPair           = "aws:ivs:playback-key-pair"
	TypeIVSPlaybackRestrictionPolicy = "aws:ivs:playback-restriction-policy"
	TypeIVSPublicKey                 = "aws:ivs:public-key"
	TypeIVSRecordingConfiguration    = "aws:ivs:recording-configuration"
	TypeIVSStage                     = "aws:ivs:stage"
	TypeIVSStorageConfiguration      = "aws:ivs:storage-configuration"
	TypeIVSStreamKey                 = "aws:ivs:stream-key"
	// Transfer (transfer_scanners.go)
	TypeTransferAgreement   = "aws:transfer:agreement"
	TypeTransferCertificate = "aws:transfer:certificate"
	TypeTransferConnector   = "aws:transfer:connector"
	TypeTransferProfile     = "aws:transfer:profile"
	TypeTransferServer      = "aws:transfer:server"
	TypeTransferUser        = "aws:transfer:user"
	TypeTransferWebApp      = "aws:transfer:web-app"
	TypeTransferWorkflow    = "aws:transfer:workflow"
	// QBusiness (qbusiness_scanners.go)
	TypeQBusinessApplication   = "aws:qbusiness:application"
	TypeQBusinessDataAccessor  = "aws:qbusiness:data-accessor"
	TypeQBusinessDataSource    = "aws:qbusiness:data-source"
	TypeQBusinessIndex         = "aws:qbusiness:index"
	TypeQBusinessPlugin        = "aws:qbusiness:plugin"
	TypeQBusinessRetriever     = "aws:qbusiness:retriever"
	TypeQBusinessWebExperience = "aws:qbusiness:web-experience"
	// OpenSearch Serverless (opensearchserverless_scanners.go)
	TypeOSSAccessPolicy    = "aws:opensearchserverless:access-policy"
	TypeOSSCollection      = "aws:opensearchserverless:collection"
	TypeOSSCollectionGroup = "aws:opensearchserverless:collection-group"
	TypeOSSLifecyclePolicy = "aws:opensearchserverless:lifecycle-policy"
	TypeOSSSecurityConfig  = "aws:opensearchserverless:security-config"
	TypeOSSSecurityPolicy  = "aws:opensearchserverless:security-policy"
	TypeOSSVpcEndpoint     = "aws:opensearchserverless:vpc-endpoint"
	// Omics (omics_scanners.go)
	TypeOmicsAnnotationStore = "aws:omics:annotation-store"
	TypeOmicsConfiguration   = "aws:omics:configuration"
	TypeOmicsReferenceStore  = "aws:omics:reference-store"
	TypeOmicsRunGroup        = "aws:omics:run-group"
	TypeOmicsSequenceStore   = "aws:omics:sequence-store"
	TypeOmicsVariantStore    = "aws:omics:variant-store"
	TypeOmicsWorkflow        = "aws:omics:workflow"
	TypeOmicsWorkflowVersion = "aws:omics:workflow-version"
	// Image Builder (imagebuilder_scanners.go)
	TypeImageBuilderComponent                 = "aws:imagebuilder:component"
	TypeImageBuilderContainerRecipe           = "aws:imagebuilder:container-recipe"
	TypeImageBuilderDistributionConfiguration = "aws:imagebuilder:distribution-configuration"
	TypeImageBuilderImagePipeline             = "aws:imagebuilder:image-pipeline"
	TypeImageBuilderImageRecipe               = "aws:imagebuilder:image-recipe"
	TypeImageBuilderInfrastructureConfig      = "aws:imagebuilder:infrastructure-configuration"
	TypeImageBuilderLifecyclePolicy           = "aws:imagebuilder:lifecycle-policy"
	TypeImageBuilderWorkflow                  = "aws:imagebuilder:workflow"
	// EMR (emr_scanners.go)
	TypeEMRCluster              = "aws:emr:cluster"
	TypeEMRInstanceFleet        = "aws:emr:instance-fleet"
	TypeEMRInstanceGroup        = "aws:emr:instance-group"
	TypeEMRSecurityConfig       = "aws:emr:security-configuration"
	TypeEMRStep                 = "aws:emr:step"
	TypeEMRStudio               = "aws:emr:studio"
	TypeEMRStudioSessionMapping = "aws:emr:studio-session-mapping"
	// CustomerProfiles (customerprofiles_scanners.go)
	TypeCPDomain                        = "aws:customer-profiles:domain"
	TypeCPCalculatedAttributeDefinition = "aws:customer-profiles:calculated-attribute-definition"
	TypeCPEventStream                   = "aws:customer-profiles:event-stream"
	TypeCPEventTrigger                  = "aws:customer-profiles:event-trigger"
	TypeCPIntegration                   = "aws:customer-profiles:integration"
	TypeCPObjectType                    = "aws:customer-profiles:object-type"
	TypeCPRecommender                   = "aws:customer-profiles:recommender"
	TypeCPSegmentDefinition             = "aws:customer-profiles:segment-definition"
	// CleanRooms (cleanrooms_scanners.go)
	TypeCleanRoomsAnalysisTemplate           = "aws:cleanrooms:analysis-template"
	TypeCleanRoomsCollaboration              = "aws:cleanrooms:collaboration"
	TypeCleanRoomsConfiguredTable            = "aws:cleanrooms:configured-table"
	TypeCleanRoomsConfiguredTableAssociation = "aws:cleanrooms:configured-table-association"
	TypeCleanRoomsIdMappingTable             = "aws:cleanrooms:id-mapping-table"
	TypeCleanRoomsIdNamespaceAssociation     = "aws:cleanrooms:id-namespace-association"
	TypeCleanRoomsMembership                 = "aws:cleanrooms:membership"
	TypeCleanRoomsPrivacyBudgetTemplate      = "aws:cleanrooms:privacy-budget-template"
	// AppConfig (appconfig_scanners.go)
	TypeAppConfigApplication                = "aws:appconfig:application"
	TypeAppConfigConfigurationProfile       = "aws:appconfig:configuration-profile"
	TypeAppConfigDeployment                 = "aws:appconfig:deployment"
	TypeAppConfigDeploymentStrategy         = "aws:appconfig:deployment-strategy"
	TypeAppConfigEnvironment                = "aws:appconfig:environment"
	TypeAppConfigExtension                  = "aws:appconfig:extension"
	TypeAppConfigExtensionAssociation       = "aws:appconfig:extension-association"
	TypeAppConfigHostedConfigurationVersion = "aws:appconfig:hosted-configuration-version"
	// SMSVoice v2 (smsvoice_scanners.go)
	TypeSMSVoiceConfigurationSet     = "aws:sms-voice:configuration-set"
	TypeSMSVoiceOptOutList           = "aws:sms-voice:opt-out-list"
	TypeSMSVoicePhoneNumber          = "aws:sms-voice:phone-number"
	TypeSMSVoicePool                 = "aws:sms-voice:pool"
	TypeSMSVoiceProtectConfiguration = "aws:sms-voice:protect-configuration"
	TypeSMSVoiceSenderID             = "aws:sms-voice:sender-id"
	// Route53GlobalResolver (route53globalresolver_scanners.go)
	TypeR53GRAccessSource          = "aws:route53globalresolver:access-source"
	TypeR53GRAccessToken           = "aws:route53globalresolver:access-token"
	TypeR53GRDNSView               = "aws:route53globalresolver:dns-view"
	TypeR53GRFirewallDomainList    = "aws:route53globalresolver:firewall-domain-list"
	TypeR53GRFirewallRule          = "aws:route53globalresolver:firewall-rule"
	TypeR53GRGlobalResolver        = "aws:route53globalresolver:global-resolver"
	TypeR53GRHostedZoneAssociation = "aws:route53globalresolver:hosted-zone-association"
	// Notifications (notifications_scanners.go)
	TypeNotificationsChannelAssociation                        = "aws:notifications:channel-association"
	TypeNotificationsEventRule                                 = "aws:notifications:event-rule"
	TypeNotificationsManagedNotificationAdditionalChannelAssoc = "aws:notifications:managed-notification-additional-channel-association"
	TypeNotificationsNotificationConfiguration                 = "aws:notifications:notification-configuration"
	TypeNotificationsNotificationHub                           = "aws:notifications:notification-hub"
	TypeNotificationsOrganizationalUnitAssociation             = "aws:notifications:organizational-unit-association"
	// Location (location_scanners.go)
	TypeLocationAPIKey             = "aws:location:api-key"
	TypeLocationGeofenceCollection = "aws:location:geofence-collection"
	TypeLocationMap                = "aws:location:map"
	TypeLocationPlaceIndex         = "aws:location:place-index"
	TypeLocationRouteCalculator    = "aws:location:route-calculator"
	TypeLocationTracker            = "aws:location:tracker"
	TypeLocationTrackerConsumer    = "aws:location:tracker-consumer"
	// DirectConnect (directconnect_scanners.go)
	TypeDirectConnectConnection                      = "aws:directconnect:connection"
	TypeDirectConnectDirectConnectGateway            = "aws:directconnect:direct-connect-gateway"
	TypeDirectConnectDirectConnectGatewayAssociation = "aws:directconnect:direct-connect-gateway-association"
	TypeDirectConnectLag                             = "aws:directconnect:lag"
	TypeDirectConnectPrivateVirtualInterface         = "aws:directconnect:private-virtual-interface"
	TypeDirectConnectPublicVirtualInterface          = "aws:directconnect:public-virtual-interface"
	TypeDirectConnectTransitVirtualInterface         = "aws:directconnect:transit-virtual-interface"
	// IoTFleetWise (iotfleetwise_scanners.go)
	TypeIoTFWCampaign        = "aws:iotfleetwise:campaign"
	TypeIoTFWDecoderManifest = "aws:iotfleetwise:decoder-manifest"
	TypeIoTFWFleet           = "aws:iotfleetwise:fleet"
	TypeIoTFWModelManifest   = "aws:iotfleetwise:model-manifest"
	TypeIoTFWSignalCatalog   = "aws:iotfleetwise:signal-catalog"
	TypeIoTFWStateTemplate   = "aws:iotfleetwise:state-template"
	TypeIoTFWVehicle         = "aws:iotfleetwise:vehicle"
	// FraudDetector (frauddetector_scanners.go)
	TypeFraudDetectorDetector   = "aws:frauddetector:detector"
	TypeFraudDetectorEntityType = "aws:frauddetector:entity-type"
	TypeFraudDetectorEventType  = "aws:frauddetector:event-type"
	TypeFraudDetectorLabel      = "aws:frauddetector:label"
	TypeFraudDetectorList       = "aws:frauddetector:list"
	TypeFraudDetectorOutcome    = "aws:frauddetector:outcome"
	TypeFraudDetectorVariable   = "aws:frauddetector:variable"
	// IoT SiteWise (iotsitewise_scanners.go)
	TypeIoTSWAccessPolicy     = "aws:iotsitewise:access-policy"
	TypeIoTSWAsset            = "aws:iotsitewise:asset"
	TypeIoTSWAssetModel       = "aws:iotsitewise:asset-model"
	TypeIoTSWComputationModel = "aws:iotsitewise:computation-model"
	TypeIoTSWDashboard        = "aws:iotsitewise:dashboard"
	TypeIoTSWDataset          = "aws:iotsitewise:dataset"
	TypeIoTSWGateway          = "aws:iotsitewise:gateway"
	TypeIoTSWPortal           = "aws:iotsitewise:portal"
	TypeIoTSWProject          = "aws:iotsitewise:project"
	// Detective (detective_scanners.go, detective_resolvers.go)
	TypeDetectiveGraph  = "aws:detective:graph"
	TypeDetectiveMember = "aws:detective:member"
	// Lake Formation (lakeformation_scanners.go, lakeformation_resolvers.go)
	TypeLakeFormationResource = "aws:lakeformation:resource"
	// SES v2 (ses_scanners.go, ses_resolvers.go)
	TypeSESEmailIdentity    = "aws:ses:email-identity"
	TypeSESConfigurationSet = "aws:ses:configuration-set"
	// SES v2 — extended (ses_v2_extended_scanners.go)
	TypeSESConfigurationSetEventDestination = "aws:ses:configuration-set-event-destination"
	TypeSESContactList                      = "aws:ses:contact-list"
	TypeSESCustomVerificationEmailTemplate  = "aws:ses:custom-verification-email-template"
	TypeSESDedicatedIpPool                  = "aws:ses:dedicated-ip-pool"
	TypeSESMultiRegionEndpoint              = "aws:ses:multi-region-endpoint"
	TypeSESTemplate                         = "aws:ses:template"
	TypeSESTenant                           = "aws:ses:tenant"
	TypeSESVdmAttributes                    = "aws:ses:vdm-attributes"
	// SES v1 — Receipt family (ses_receipt_scanners.go)
	TypeSESReceiptFilter  = "aws:ses:receipt-filter"
	TypeSESReceiptRule    = "aws:ses:receipt-rule"
	TypeSESReceiptRuleSet = "aws:ses:receipt-rule-set"
	// SES — MailManager family (ses_mailmanager_scanners.go)
	TypeSESMailManagerAddonInstance     = "aws:ses:mailmanager-addon-instance"
	TypeSESMailManagerAddonSubscription = "aws:ses:mailmanager-addon-subscription"
	TypeSESMailManagerAddressList       = "aws:ses:mailmanager-address-list"
	TypeSESMailManagerArchive           = "aws:ses:mailmanager-archive"
	TypeSESMailManagerIngressPoint      = "aws:ses:mailmanager-ingress-point"
	TypeSESMailManagerRelay             = "aws:ses:mailmanager-relay"
	TypeSESMailManagerRuleSet           = "aws:ses:mailmanager-rule-set"
	TypeSESMailManagerTrafficPolicy     = "aws:ses:mailmanager-traffic-policy"
	// Pinpoint — Core (pinpoint_scanners.go)
	TypePinpointApp                 = "aws:pinpoint:app"
	TypePinpointApplicationSettings = "aws:pinpoint:application-settings"
	TypePinpointEventStream         = "aws:pinpoint:event-stream"
	TypePinpointCampaign            = "aws:pinpoint:campaign"
	TypePinpointSegment             = "aws:pinpoint:segment"
	// Pinpoint — Channels (pinpoint_channels_scanners.go)
	TypePinpointADMChannel             = "aws:pinpoint:adm-channel"
	TypePinpointAPNSChannel            = "aws:pinpoint:apns-channel"
	TypePinpointAPNSSandboxChannel     = "aws:pinpoint:apns-sandbox-channel"
	TypePinpointAPNSVoipChannel        = "aws:pinpoint:apns-voip-channel"
	TypePinpointAPNSVoipSandboxChannel = "aws:pinpoint:apns-voip-sandbox-channel"
	TypePinpointBaiduChannel           = "aws:pinpoint:baidu-channel"
	TypePinpointEmailChannel           = "aws:pinpoint:email-channel"
	TypePinpointGCMChannel             = "aws:pinpoint:gcm-channel"
	TypePinpointSMSChannel             = "aws:pinpoint:sms-channel"
	TypePinpointVoiceChannel           = "aws:pinpoint:voice-channel"
	// Pinpoint — Templates (pinpoint_templates_scanners.go)
	TypePinpointEmailTemplate = "aws:pinpoint:email-template"
	TypePinpointInAppTemplate = "aws:pinpoint:in-app-template"
	TypePinpointPushTemplate  = "aws:pinpoint:push-template"
	TypePinpointSmsTemplate   = "aws:pinpoint:sms-template"
	// DataZone (datazone_scanners.go)
	TypeDataZoneDomain                            = "aws:datazone:domain"
	TypeDataZoneDomainUnit                        = "aws:datazone:domain-unit"
	TypeDataZoneProject                           = "aws:datazone:project"
	TypeDataZoneProjectProfile                    = "aws:datazone:project-profile"
	TypeDataZoneProjectMembership                 = "aws:datazone:project-membership"
	TypeDataZoneEnvironment                       = "aws:datazone:environment"
	TypeDataZoneEnvironmentProfile                = "aws:datazone:environment-profile"
	TypeDataZoneEnvironmentActions                = "aws:datazone:environment-actions"
	TypeDataZoneEnvironmentBlueprintConfiguration = "aws:datazone:environment-blueprint-configuration"
	TypeDataZoneDataSource                        = "aws:datazone:data-source"
	TypeDataZoneConnection                        = "aws:datazone:connection"
	TypeDataZoneSubscriptionTarget                = "aws:datazone:subscription-target"
	// NetworkManager (networkmanager_scanners.go) — global service hosted in us-west-2
	TypeNetworkManagerGlobalNetwork                      = "aws:networkmanager:global-network"
	TypeNetworkManagerCoreNetwork                        = "aws:networkmanager:core-network"
	TypeNetworkManagerSite                               = "aws:networkmanager:site"
	TypeNetworkManagerDevice                             = "aws:networkmanager:device"
	TypeNetworkManagerLink                               = "aws:networkmanager:link"
	TypeNetworkManagerLinkAssociation                    = "aws:networkmanager:link-association"
	TypeNetworkManagerCustomerGatewayAssociation         = "aws:networkmanager:customer-gateway-association"
	TypeNetworkManagerTransitGatewayRegistration         = "aws:networkmanager:transit-gateway-registration"
	TypeNetworkManagerVpcAttachment                      = "aws:networkmanager:vpc-attachment"
	TypeNetworkManagerConnectAttachment                  = "aws:networkmanager:connect-attachment"
	TypeNetworkManagerSiteToSiteVpnAttachment            = "aws:networkmanager:site-to-site-vpn-attachment"
	TypeNetworkManagerDirectConnectGatewayAttachment     = "aws:networkmanager:direct-connect-gateway-attachment"
	TypeNetworkManagerTransitGatewayRouteTableAttachment = "aws:networkmanager:transit-gateway-route-table-attachment"
	TypeNetworkManagerTransitGatewayPeering              = "aws:networkmanager:transit-gateway-peering"
	TypeNetworkManagerConnectPeer                        = "aws:networkmanager:connect-peer"
	TypeNetworkManagerCoreNetworkPrefixListAssociation   = "aws:networkmanager:core-network-prefix-list-association"
	// Greengrass v1 (greengrass_scanners.go) — deprecated by AWS but still has CFN types
	TypeGreengrassConnectorDefinition           = "aws:greengrass:connector-definition"
	TypeGreengrassConnectorDefinitionVersion    = "aws:greengrass:connector-definition-version"
	TypeGreengrassCoreDefinition                = "aws:greengrass:core-definition"
	TypeGreengrassCoreDefinitionVersion         = "aws:greengrass:core-definition-version"
	TypeGreengrassDeviceDefinition              = "aws:greengrass:device-definition"
	TypeGreengrassDeviceDefinitionVersion       = "aws:greengrass:device-definition-version"
	TypeGreengrassFunctionDefinition            = "aws:greengrass:function-definition"
	TypeGreengrassFunctionDefinitionVersion     = "aws:greengrass:function-definition-version"
	TypeGreengrassLoggerDefinition              = "aws:greengrass:logger-definition"
	TypeGreengrassLoggerDefinitionVersion       = "aws:greengrass:logger-definition-version"
	TypeGreengrassResourceDefinition            = "aws:greengrass:resource-definition"
	TypeGreengrassResourceDefinitionVersion     = "aws:greengrass:resource-definition-version"
	TypeGreengrassSubscriptionDefinition        = "aws:greengrass:subscription-definition"
	TypeGreengrassSubscriptionDefinitionVersion = "aws:greengrass:subscription-definition-version"
	TypeGreengrassGroup                         = "aws:greengrass:group"
	TypeGreengrassGroupVersion                  = "aws:greengrass:group-version"
	// BedrockAgentCore (bedrockagentcore_scanners.go)
	TypeBedrockAgentCoreApiKeyCredentialProvider = "aws:bedrockagentcore:api-key-credential-provider"
	TypeBedrockAgentCoreBrowserCustom            = "aws:bedrockagentcore:browser-custom"
	TypeBedrockAgentCoreBrowserProfile           = "aws:bedrockagentcore:browser-profile"
	TypeBedrockAgentCoreCodeInterpreterCustom    = "aws:bedrockagentcore:code-interpreter-custom"
	TypeBedrockAgentCoreEvaluator                = "aws:bedrockagentcore:evaluator"
	TypeBedrockAgentCoreGateway                  = "aws:bedrockagentcore:gateway"
	TypeBedrockAgentCoreGatewayTarget            = "aws:bedrockagentcore:gateway-target"
	TypeBedrockAgentCoreMemory                   = "aws:bedrockagentcore:memory"
	TypeBedrockAgentCoreOAuth2CredentialProvider = "aws:bedrockagentcore:oauth2-credential-provider"
	TypeBedrockAgentCoreOnlineEvaluationConfig   = "aws:bedrockagentcore:online-evaluation-config"
	TypeBedrockAgentCorePolicy                   = "aws:bedrockagentcore:policy"
	TypeBedrockAgentCorePolicyEngine             = "aws:bedrockagentcore:policy-engine"
	TypeBedrockAgentCoreRuntime                  = "aws:bedrockagentcore:runtime"
	TypeBedrockAgentCoreRuntimeEndpoint          = "aws:bedrockagentcore:runtime-endpoint"
	TypeBedrockAgentCoreWorkloadIdentity         = "aws:bedrockagentcore:workload-identity"
	// VpcLattice (vpclattice_scanners.go)
	TypeVpcLatticeService                           = "aws:vpclattice:service"
	TypeVpcLatticeServiceNetwork                    = "aws:vpclattice:service-network"
	TypeVpcLatticeListener                          = "aws:vpclattice:listener"
	TypeVpcLatticeRule                              = "aws:vpclattice:rule"
	TypeVpcLatticeTargetGroup                       = "aws:vpclattice:target-group"
	TypeVpcLatticeAccessLogSubscription             = "aws:vpclattice:access-log-subscription"
	TypeVpcLatticeAuthPolicy                        = "aws:vpclattice:auth-policy"
	TypeVpcLatticeResourcePolicy                    = "aws:vpclattice:resource-policy"
	TypeVpcLatticeDomainVerification                = "aws:vpclattice:domain-verification"
	TypeVpcLatticeResourceConfiguration             = "aws:vpclattice:resource-configuration"
	TypeVpcLatticeResourceGateway                   = "aws:vpclattice:resource-gateway"
	TypeVpcLatticeServiceNetworkResourceAssociation = "aws:vpclattice:service-network-resource-association"
	TypeVpcLatticeServiceNetworkServiceAssociation  = "aws:vpclattice:service-network-service-association"
	TypeVpcLatticeServiceNetworkVpcAssociation      = "aws:vpclattice:service-network-vpc-association"
	// Inspector v2 (inspector_scanners.go, inspector_resolvers.go)
	TypeInspector2Filter = "aws:inspector2:filter"
	TypeInspector2Member = "aws:inspector2:member"
	// Glue Data Catalog (glue_scanners.go, glue_resolvers.go)
	TypeGlueDatabase = "aws:glue:database"
	TypeGlueTable    = "aws:glue:table"
	// Bedrock — Agents family (bedrock_agents_scanners.go)
	TypeBedrockAgent         = "aws:bedrock:agent"
	TypeBedrockAgentAlias    = "aws:bedrock:agent-alias"
	TypeBedrockKnowledgeBase = "aws:bedrock:knowledge-base"
	TypeBedrockDataSource    = "aws:bedrock:data-source"
	TypeBedrockFlow          = "aws:bedrock:flow"
	TypeBedrockFlowAlias     = "aws:bedrock:flow-alias"
	TypeBedrockFlowVersion   = "aws:bedrock:flow-version"
	TypeBedrockPrompt        = "aws:bedrock:prompt"
	TypeBedrockPromptVersion = "aws:bedrock:prompt-version"
	// Bedrock — Foundation family (bedrock_foundation_scanners.go)
	TypeBedrockGuardrail                       = "aws:bedrock:guardrail"
	TypeBedrockGuardrailVersion                = "aws:bedrock:guardrail-version"
	TypeBedrockAutomatedReasoningPolicy        = "aws:bedrock:automated-reasoning-policy"
	TypeBedrockAutomatedReasoningPolicyVersion = "aws:bedrock:automated-reasoning-policy-version"
	TypeBedrockIntelligentPromptRouter         = "aws:bedrock:intelligent-prompt-router"
	TypeBedrockApplicationInferenceProfile     = "aws:bedrock:application-inference-profile"
	TypeBedrockEnforcedGuardrailConfiguration  = "aws:bedrock:enforced-guardrail-configuration"
	// Glue — Schema (glue_schema_scanners.go)
	TypeGlueRegistry              = "aws:glue:registry"
	TypeGlueSchema                = "aws:glue:schema"
	TypeGlueSchemaVersion         = "aws:glue:schema-version"
	TypeGlueSchemaVersionMetadata = "aws:glue:schema-version-metadata"
	// Glue — Catalog family (glue_catalog_scanners.go)
	TypeGlueCrawler    = "aws:glue:crawler"
	TypeGlueConnection = "aws:glue:connection"
	TypeGlueClassifier = "aws:glue:classifier"
	// Glue — Misc family (glue_misc_scanners.go)
	TypeGlueCatalog                       = "aws:glue:catalog"
	TypeGlueCustomEntityType              = "aws:glue:custom-entity-type"
	TypeGlueDataCatalogEncryptionSettings = "aws:glue:data-catalog-encryption-settings"
	TypeGlueDataQualityRuleset            = "aws:glue:data-quality-ruleset"
	TypeGlueIdentityCenterConfiguration   = "aws:glue:identity-center-configuration"
	TypeGlueIntegration                   = "aws:glue:integration"
	TypeGlueIntegrationResourceProperty   = "aws:glue:integration-resource-property"
	TypeGlueSecurityConfiguration         = "aws:glue:security-configuration"
	TypeGlueUsageProfile                  = "aws:glue:usage-profile"
	// Glue — Jobs family (glue_jobs_scanners.go)
	TypeGlueJob         = "aws:glue:job"
	TypeGlueTrigger     = "aws:glue:trigger"
	TypeGlueWorkflow    = "aws:glue:workflow"
	TypeGlueMLTransform = "aws:glue:ml-transform"
	TypeGlueDevEndpoint = "aws:glue:dev-endpoint"
	// Athena (athena_scanners.go, athena_resolvers.go)
	TypeAthenaWorkgroup   = "aws:athena:workgroup"
	TypeAthenaDataCatalog = "aws:athena:datacatalog"
	// Redshift (redshift_scanners.go, redshift_resolvers.go)
	TypeRedshiftCluster               = "aws:redshift:cluster"
	TypeRedshiftSubnetGroup           = "aws:redshift:subnet-group"
	TypeRedshiftClusterParameterGroup = "aws:redshift:cluster-parameter-group"
	TypeRedshiftClusterSecurityGroup  = "aws:redshift:cluster-security-group"
	TypeRedshiftEndpointAccess        = "aws:redshift:endpoint-access"
	TypeRedshiftEndpointAuthorization = "aws:redshift:endpoint-authorization"
	TypeRedshiftEventSubscription     = "aws:redshift:event-subscription"
	TypeRedshiftIntegration           = "aws:redshift:integration"
	TypeRedshiftScheduledAction       = "aws:redshift:scheduled-action"
	// OpenSearch (opensearch_scanners.go, opensearch_resolvers.go)
	TypeOpenSearchDomain = "aws:opensearch:domain"
	// DocumentDB (docdb_scanners.go, docdb_resolvers.go)
	TypeDocDBCluster  = "aws:docdb:cluster"
	TypeDocDBInstance = "aws:docdb:instance"
	// Neptune (neptune_scanners.go, neptune_resolvers.go)
	TypeNeptuneCluster  = "aws:neptune:cluster"
	TypeNeptuneInstance = "aws:neptune:instance"
	// Service Catalog (servicecatalog_scanners.go, servicecatalog_resolvers.go)
	TypeServiceCatalogPortfolio = "aws:servicecatalog:portfolio"
	TypeServiceCatalogProduct   = "aws:servicecatalog:product"
	// ServiceCatalog — extended (servicecatalog_extended_scanners.go)
	TypeServiceCatalogAcceptedPortfolioShare           = "aws:servicecatalog:accepted-portfolio-share"
	TypeServiceCatalogCloudFormationProvisionedProduct = "aws:servicecatalog:cloudformation-provisioned-product"
	TypeServiceCatalogServiceAction                    = "aws:servicecatalog:service-action"
	TypeServiceCatalogTagOption                        = "aws:servicecatalog:tag-option"
	TypeServiceCatalogPortfolioShare                   = "aws:servicecatalog:portfolio-share"
	TypeServiceCatalogPortfolioPrincipalAssociation    = "aws:servicecatalog:portfolio-principal-association"
	TypeServiceCatalogTagOptionAssociation             = "aws:servicecatalog:tag-option-association"
	TypeServiceCatalogLaunchRoleConstraint             = "aws:servicecatalog:launch-role-constraint"
	TypeServiceCatalogLaunchNotificationConstraint     = "aws:servicecatalog:launch-notification-constraint"
	TypeServiceCatalogLaunchTemplateConstraint         = "aws:servicecatalog:launch-template-constraint"
	TypeServiceCatalogResourceUpdateConstraint         = "aws:servicecatalog:resource-update-constraint"
	TypeServiceCatalogStackSetConstraint               = "aws:servicecatalog:stack-set-constraint"
	// MediaLive (medialive_scanners.go)
	TypeMediaLiveChannel                      = "aws:medialive:channel"
	TypeMediaLiveChannelPlacementGroup        = "aws:medialive:channel-placement-group"
	TypeMediaLiveCloudWatchAlarmTemplate      = "aws:medialive:cloudwatch-alarm-template"
	TypeMediaLiveCloudWatchAlarmTemplateGroup = "aws:medialive:cloudwatch-alarm-template-group"
	TypeMediaLiveCluster                      = "aws:medialive:cluster"
	TypeMediaLiveEventBridgeRuleTemplate      = "aws:medialive:eventbridge-rule-template"
	TypeMediaLiveEventBridgeRuleTemplateGroup = "aws:medialive:eventbridge-rule-template-group"
	TypeMediaLiveInput                        = "aws:medialive:input"
	TypeMediaLiveInputSecurityGroup           = "aws:medialive:input-security-group"
	TypeMediaLiveMultiplex                    = "aws:medialive:multiplex"
	TypeMediaLiveMultiplexProgram             = "aws:medialive:multiplexprogram"
	TypeMediaLiveNetwork                      = "aws:medialive:network"
	TypeMediaLiveSdiSource                    = "aws:medialive:sdi-source"
	TypeMediaLiveSignalMap                    = "aws:medialive:signal-map"
	// DataSync (datasync_scanners.go)
	TypeDataSyncAgent                 = "aws:datasync:agent"
	TypeDataSyncTask                  = "aws:datasync:task"
	TypeDataSyncLocationEFS           = "aws:datasync:location-efs"
	TypeDataSyncLocationNFS           = "aws:datasync:location-nfs"
	TypeDataSyncLocationSMB           = "aws:datasync:location-smb"
	TypeDataSyncLocationS3            = "aws:datasync:location-s3"
	TypeDataSyncLocationHDFS          = "aws:datasync:location-hdfs"
	TypeDataSyncLocationAzureBlob     = "aws:datasync:location-azure-blob"
	TypeDataSyncLocationObjectStorage = "aws:datasync:location-object-storage"
	TypeDataSyncLocationFSxLustre     = "aws:datasync:location-fsx-lustre"
	TypeDataSyncLocationFSxONTAP      = "aws:datasync:location-fsx-ontap"
	TypeDataSyncLocationFSxOpenZFS    = "aws:datasync:location-fsx-openzfs"
	TypeDataSyncLocationFSxWindows    = "aws:datasync:location-fsx-windows"
	// Audit Manager (auditmanager_scanners.go, auditmanager_resolvers.go)
	TypeAuditManagerAssessment = "aws:auditmanager:assessment"
	TypeAuditManagerFramework  = "aws:auditmanager:framework"
	TypeAuditManagerControl    = "aws:auditmanager:control"
	// Control Tower (controltower_scanners.go, controltower_resolvers.go)
	TypeControlTowerLandingZone     = "aws:controltower:landing-zone"
	TypeControlTowerEnabledBaseline = "aws:controltower:enabled-baseline"
	// App Runner (apprunner_scanners.go, apprunner_resolvers.go)
	TypeAppRunnerService                    = "aws:apprunner:service"
	TypeAppRunnerVPCConnector               = "aws:apprunner:vpc-connector"
	TypeAppRunnerAutoScalingConfiguration   = "aws:apprunner:auto-scaling-configuration"
	TypeAppRunnerObservabilityConfiguration = "aws:apprunner:observability-configuration"
	TypeAppRunnerVpcIngressConnection       = "aws:apprunner:vpc-ingress-connection"
	// Batch (batch_scanners.go, batch_resolvers.go)
	TypeBatchComputeEnvironment = "aws:batch:compute-environment"
	TypeBatchJobQueue           = "aws:batch:job-queue"
	TypeBatchJobDefinition      = "aws:batch:job-definition"
	TypeBatchSchedulingPolicy   = "aws:batch:scheduling-policy"
	TypeBatchConsumableResource = "aws:batch:consumable-resource"
	TypeBatchServiceEnvironment = "aws:batch:service-environment"
	TypeBatchQuotaShare         = "aws:batch:quota-share"
	// Lightsail (lightsail_scanners.go)
	TypeLightsailInstance         = "aws:lightsail:instance"
	TypeLightsailDatabase         = "aws:lightsail:database"
	TypeLightsailContainerService = "aws:lightsail:container-service"
	// Lightsail — extended (lightsail_extended_scanners.go)
	TypeLightsailAlarm                      = "aws:lightsail:alarm"
	TypeLightsailBucket                     = "aws:lightsail:bucket"
	TypeLightsailCertificate                = "aws:lightsail:certificate"
	TypeLightsailDatabaseSnapshot           = "aws:lightsail:database-snapshot"
	TypeLightsailDisk                       = "aws:lightsail:disk"
	TypeLightsailDiskSnapshot               = "aws:lightsail:disk-snapshot"
	TypeLightsailDistribution               = "aws:lightsail:distribution"
	TypeLightsailDomain                     = "aws:lightsail:domain"
	TypeLightsailInstanceSnapshot           = "aws:lightsail:instance-snapshot"
	TypeLightsailLoadBalancer               = "aws:lightsail:load-balancer"
	TypeLightsailLoadBalancerTlsCertificate = "aws:lightsail:load-balancer-tls-certificate"
	TypeLightsailStaticIp                   = "aws:lightsail:static-ip"
	// Elastic Beanstalk (elasticbeanstalk_scanners.go, elasticbeanstalk_resolvers.go)
	TypeBeanstalkApplication = "aws:elasticbeanstalk:application"
	TypeBeanstalkEnvironment = "aws:elasticbeanstalk:environment"
	// IAM Access Analyzer (accessanalyzer_scanners.go, accessanalyzer_resolvers.go)
	TypeAccessAnalyzerAnalyzer = "aws:accessanalyzer:analyzer"
	// ACM Private CA permissions (acmpca_scanners.go, acmpca_resolvers.go)
	TypeACMPCAPermission = "aws:acm-pca:permission"
	// CloudWatch AIOps investigation groups (aiops_scanners.go, aiops_resolvers.go)
	TypeAIOpsInvestigationGroup = "aws:aiops:investigation-group"
	// Amazon MQ (mq_scanners.go, mq_resolvers.go)
	TypeMQBroker                   = "aws:mq:broker"
	TypeMQConfiguration            = "aws:mq:configuration"
	TypeMQConfigurationAssociation = "aws:mq:configuration-association"
	// Amplify (amplify_scanners.go, amplify_resolvers.go)
	TypeAmplifyApp    = "aws:amplify:app"
	TypeAmplifyBranch = "aws:amplify:branch"
	TypeAmplifyDomain = "aws:amplify:domain"
	// API Gateway v2 — VPC Link (apigateway_v2_scanners.go); separate from
	// the v1 TypeAPIGatewayVpcLink which targets a different SDK module
	// (apigateway, not apigatewayv2).
	TypeAPIGatewayV2VpcLink = "aws:apigatewayv2:vpc-link"
	// AppFlow (appflow_scanners.go, appflow_resolvers.go)
	// Application Auto Scaling (applicationautoscaling_scanners.go)
	TypeApplicationAutoScalingScalableTarget = "aws:application-autoscaling:scalable-target"
	TypeApplicationAutoScalingScalingPolicy  = "aws:application-autoscaling:scaling-policy"
	TypeAppFlowFlow                          = "aws:appflow:flow"
	TypeAppFlowConnector                     = "aws:appflow:connector"
	TypeAppFlowConnectorProfile              = "aws:appflow:connector-profile"
	// AppIntegrations (appintegrations_scanners.go, appintegrations_resolvers.go)
	TypeAppIntegrationsApplication      = "aws:appintegrations:application"
	TypeAppIntegrationsDataIntegration  = "aws:appintegrations:data-integration"
	TypeAppIntegrationsEventIntegration = "aws:appintegrations:event-integration"
	// CloudWatch Application Insights (applicationinsights_scanners.go, applicationinsights_resolvers.go)
	TypeApplicationInsightsApplication = "aws:applicationinsights:application"
	// CloudWatch Application Signals (applicationsignals_scanners.go, applicationsignals_resolvers.go)
	TypeApplicationSignalsSLO                   = "aws:applicationsignals:service-level-objective"
	TypeApplicationSignalsGroupingConfiguration = "aws:applicationsignals:grouping-configuration"
	// Amazon Managed Prometheus / APS (aps_scanners.go, aps_resolvers.go); SDK module is `amp`.
	TypeAPSWorkspace = "aws:aps:workspace"
	TypeAPSScraper   = "aws:aps:scraper"
	// AppMesh (appmesh_scanners.go).
	TypeAppMeshMesh           = "aws:appmesh:mesh"
	TypeAppMeshGatewayRoute   = "aws:appmesh:gateway-route"
	TypeAppMeshRoute          = "aws:appmesh:route"
	TypeAppMeshVirtualGateway = "aws:appmesh:virtual-gateway"
	TypeAppMeshVirtualNode    = "aws:appmesh:virtual-node"
	TypeAppMeshVirtualRouter  = "aws:appmesh:virtual-router"
	TypeAppMeshVirtualService = "aws:appmesh:virtual-service"
	// RTBFabric (rtbfabric_scanners.go). Real-time bidding fabric.
	TypeRTBFabricLink             = "aws:rtbfabric:link"
	TypeRTBFabricRequesterGateway = "aws:rtbfabric:requester-gateway"
	TypeRTBFabricResponderGateway = "aws:rtbfabric:responder-gateway"
	// S3Tables (s3tables_scanners.go).
	TypeS3TablesNamespace         = "aws:s3tables:namespace"
	TypeS3TablesTable             = "aws:s3tables:table"
	TypeS3TablesTableBucket       = "aws:s3tables:table-bucket"
	TypeS3TablesTableBucketPolicy = "aws:s3tables:table-bucket-policy"
	TypeS3TablesTablePolicy       = "aws:s3tables:table-policy"
	// ServiceDiscovery / Cloud Map (servicediscovery_scanners.go).
	TypeServiceDiscoveryHttpNamespace       = "aws:servicediscovery:http-namespace"
	TypeServiceDiscoveryPrivateDnsNamespace = "aws:servicediscovery:private-dns-namespace"
	TypeServiceDiscoveryPublicDnsNamespace  = "aws:servicediscovery:public-dns-namespace"
	TypeServiceDiscoveryService             = "aws:servicediscovery:service"
	TypeServiceDiscoveryInstance            = "aws:servicediscovery:instance"
	// Timestream (timestream_scanners.go); spans timestreamwrite,
	// timestreamquery, and timestreaminfluxdb SDKs.
	TypeTimestreamDatabase         = "aws:timestream:database"
	TypeTimestreamInfluxDBCluster  = "aws:timestream:influx-db-cluster"
	TypeTimestreamInfluxDBInstance = "aws:timestream:influx-db-instance"
	TypeTimestreamScheduledQuery   = "aws:timestream:scheduled-query"
	TypeTimestreamTable            = "aws:timestream:table"
	// DataBrew (databrew_scanners.go).
	TypeDataBrewDataset  = "aws:databrew:dataset"
	TypeDataBrewJob      = "aws:databrew:job"
	TypeDataBrewProject  = "aws:databrew:project"
	TypeDataBrewRecipe   = "aws:databrew:recipe"
	TypeDataBrewRuleset  = "aws:databrew:ruleset"
	TypeDataBrewSchedule = "aws:databrew:schedule"
	// FSx (fsx_scanners.go).
	TypeFSxFileSystem                = "aws:fsx:file-system"
	TypeFSxDataRepositoryAssociation = "aws:fsx:data-repository-association"
	TypeFSxSnapshot                  = "aws:fsx:snapshot"
	TypeFSxStorageVirtualMachine     = "aws:fsx:storage-virtual-machine"
	TypeFSxVolume                    = "aws:fsx:volume"
	TypeFSxS3AccessPointAttachment   = "aws:fsx:s3-access-point-attachment"
	// LakeFormation (lakeformation_scanners.go).
	TypeLakeFormationDataCellsFilter      = "aws:lakeformation:data-cells-filter"
	TypeLakeFormationDataLakeSettings     = "aws:lakeformation:data-lake-settings"
	TypeLakeFormationPrincipalPermissions = "aws:lakeformation:principal-permissions"
	TypeLakeFormationTag                  = "aws:lakeformation:tag"
	// MediaTailor (mediatailor_scanners.go).
	TypeMediaTailorChannel               = "aws:mediatailor:channel"
	TypeMediaTailorChannelPolicy         = "aws:mediatailor:channel-policy"
	TypeMediaTailorLiveSource            = "aws:mediatailor:live-source"
	TypeMediaTailorPlaybackConfiguration = "aws:mediatailor:playback-configuration"
	TypeMediaTailorSourceLocation        = "aws:mediatailor:source-location"
	TypeMediaTailorVodSource             = "aws:mediatailor:vod-source"
	// MemoryDB (memorydb_scanners.go).
	TypeMemoryDBACL                = "aws:memorydb:acl"
	TypeMemoryDBCluster            = "aws:memorydb:cluster"
	TypeMemoryDBMultiRegionCluster = "aws:memorydb:multi-region-cluster"
	TypeMemoryDBParameterGroup     = "aws:memorydb:parameter-group"
	TypeMemoryDBSubnetGroup        = "aws:memorydb:subnet-group"
	TypeMemoryDBUser               = "aws:memorydb:user"
	// ObservabilityAdmin (observabilityadmin_scanners.go). Disco service segment
	// "observabilityadmin"; CFN segment "ObservabilityAdmin".
	TypeObservabilityAdminOrganizationCentralizationRule = "aws:observabilityadmin:organization-centralization-rule"
	TypeObservabilityAdminOrganizationTelemetryRule      = "aws:observabilityadmin:organization-telemetry-rule"
	TypeObservabilityAdminS3TableIntegration             = "aws:observabilityadmin:s3-table-integration"
	TypeObservabilityAdminTelemetryEnrichment            = "aws:observabilityadmin:telemetry-enrichment"
	TypeObservabilityAdminTelemetryPipelines             = "aws:observabilityadmin:telemetry-pipelines"
	TypeObservabilityAdminTelemetryRule                  = "aws:observabilityadmin:telemetry-rule"
	// ARC Region Switch (arcregionswitch_scanners.go, arcregionswitch_resolvers.go).
	TypeARCRegionSwitchPlan = "aws:arc-region-switch:plan"
	// ARC Zonal Shift (arczonalshift_scanners.go, arczonalshift_resolvers.go).
	TypeARCZonalShiftObserverStatus = "aws:arc-zonal-shift:autoshift-observer-notification-status"
	TypeARCZonalShiftConfiguration  = "aws:arc-zonal-shift:zonal-autoshift-configuration"
	// Athena capacity reservations (athena_scanners.go).
	TypeAthenaCapacityReservation = "aws:athena:capacity-reservation"
	// EC2 Auto Scaling (autoscaling_scanners.go, autoscaling_resolvers.go).
	TypeAutoScalingGroup               = "aws:autoscaling:auto-scaling-group"
	TypeAutoScalingLaunchConfiguration = "aws:autoscaling:launch-configuration"
	TypeAutoScalingLifecycleHook       = "aws:autoscaling:lifecycle-hook"
	TypeAutoScalingScalingPolicy       = "aws:autoscaling:scaling-policy"
	TypeAutoScalingScheduledAction     = "aws:autoscaling:scheduled-action"
	TypeAutoScalingWarmPool            = "aws:autoscaling:warm-pool"
	// AWS Auto Scaling (a.k.a. AutoScalingPlans). Disco service segment
	// "autoscaling-plans"; CFN segment "AutoScalingPlans".
	TypeAutoScalingPlansScalingPlan = "aws:autoscaling-plans:scaling-plan"
)
