package aws

// leafTypes is the central registry of disco types whose scanner upserts
// rows but which have no outbound refs to other scanned resources. These
// are excluded from `disco coverage --missing-resolvers` so the orphan
// inventory only contains genuinely wire-able candidates.
//
// Adding a type here is equivalent to declaring "no resolver will ever
// emit edges from this type". If an out-edge is later identified, drop
// the entry and ship the resolver.
//
// Categories represented (in order below):
//  1. Account/region singleton configs — `*:account`, `*:account-summary`,
//     `*:account-password-policy`, `*:credential-report`, `*:vdm-attributes`,
//     `*:notification-hub`, etc.
//  2. Public-access / encryption / replication / registry singletons.
//  3. Catalog leaves — fraud-detector primitives, Bedrock guardrail/router/
//     intelligent-prompt-router, gamelift build/script catalog rows.
//  4. SES Mail Manager + IoTWireless types whose Get/Describe ops add no
//     useful cross-refs (per Tier C1.4 verify outcome).
//  5. Long-tail singletons: notification-rule, support-app account-alias,
//     uxc account-customization, etc.
//
// Precedent shape mirrors `nonRDSEngines` in `rds_scanners.go` (centralised
// per-package set) and the `internal/providers/CLAUDE.md` "managed-by-
// provider" pattern, except this set is consumed at coverage-render time
// not scan time.
var leafTypes = map[string]bool{
	// Account/region singleton configs.
	"aws:acm:account":                          true,
	"aws:apigateway:account":                   true,
	"aws:iam:account-summary":                  true,
	"aws:iam:account-password-policy":          true,
	"aws:iam:credential-report":                true,
	"aws:iam:service-last-accessed-detail":     true,
	"aws:logs:account-policy":                  true,
	"aws:ses:vdm-attributes":                   true,
	"aws:support-app:account-alias":            true,
	"aws:uxc:account-customization":            true,
	"aws:notifications:notification-hub":       true,
	"aws:notifications-contacts:email-contact": true,
	// Public-access, encryption, replication, registry singletons.
	"aws:ec2:snapshot-block-public-access":            true,
	"aws:ec2:vpc-block-public-access-exclusion":       true,
	"aws:ec2:vpc-block-public-access-options":         true,
	"aws:ec2:vpc-encryption-control":                  true,
	"aws:ec2:capacity-manager-data-export":            true,
	"aws:ec2:network-performance-metric-subscription": true,
	"aws:ec2:network-insights-access-scope":           true,
	"aws:ec2:traffic-mirror-filter":                   true,
	"aws:ec2:vpn-concentrator":                        true,
	"aws:ec2:dhcp-options":                            true,
	"aws:ec2:host":                                    true,
	"aws:ec2:placement-group":                         true,
	"aws:ec2:customer-gateway":                        true,
	"aws:ec2:prefix-list":                             true,
	"aws:ec2:egress-only-internet-gateway":            true,
	"aws:ec2:vpc":                                     true,
	"aws:ec2:key-pair":                                true,
	"aws:ec2:verified-access-trust-provider":          true,
	"aws:ecr:public-repository":                       true,
	"aws:ecr:pull-through-cache-rule":                 true,
	"aws:ecr:pull-time-update-exclusion":              true,
	"aws:ecr:registry-policy":                         true,
	"aws:ecr:registry-scanning-configuration":         true,
	"aws:ecr:replication-configuration":               true,
	"aws:ecr:repository-creation-template":            true,
	"aws:ecr:signing-configuration":                   true,
	"aws:event-schemas:registry-policy":               true,
	"aws:iot:encryption-configuration":                true,
	"aws:iot:logging":                                 true,
	"aws:iot:resource-specific-logging":               true,
	"aws:iot:scheduled-audit":                         true,
	"aws:iot:billing-group":                           true,
	"aws:iot:thing-type":                              true,
	"aws:iot:certificate":                             true,
	"aws:iot:ca-certificate":                          true,
	"aws:iot:certificate-provider":                    true,
	"aws:iot:command":                                 true,
	"aws:iot:dimension":                               true,
	"aws:iot:policy":                                  true,
	// CloudWatch dashboard / anomaly-detector / mute-rule / insight-rule /
	// metric-stream — only metric-stream has out-edges (already wired);
	// the rest are pure config singletons.
	"aws:cloudwatch:dashboard":        true,
	"aws:cloudwatch:alarm-mute-rule":  true,
	"aws:cloudwatch:anomaly-detector": true,
	"aws:cloudwatch:insight-rule":     true,
	"aws:cloudwatch:otel-enrichment":  true,
	// Macie account singletons.
	"aws:macie:session":                true,
	"aws:macie:custom-data-identifier": true,
	"aws:macie:findings-filter":        true,
	// Athena / S3 leaves.
	"aws:athena:capacity-reservation":    true,
	"aws:s3:account-public-access-block": true,
	// Bedrock catalog leaves (guardrail body, router, inference-profile
	// — config-only, no out-refs to scanned types).
	"aws:bedrock:guardrail":                            true,
	"aws:bedrock:application-inference-profile":        true,
	"aws:bedrock:enforced-guardrail-configuration":     true,
	"aws:bedrock:intelligent-prompt-router":            true,
	"aws:bedrock:prompt":                               true,
	"aws:bedrock:flow":                                 true,
	"aws:bedrock:automated-reasoning-policy":           true,
	"aws:bedrockagentcore:workload-identity":           true,
	"aws:bedrockagentcore:api-key-credential-provider": true,
	"aws:bedrockagentcore:oauth2-credential-provider":  true,
	"aws:bedrockagentcore:browser-custom":              true,
	"aws:bedrockagentcore:code-interpreter-custom":     true,
	"aws:bedrockagentcore:gateway":                     true,
	"aws:bedrockagentcore:memory":                      true,
	"aws:bedrockagentcore:policy-engine":               true,
	"aws:bedrockagentcore:runtime":                     true,
	"aws:bedrockagentcore:browser-profile":             true,
	"aws:bedrockagentcore:evaluator":                   true,
	"aws:bedrockagentcore:online-evaluation-config":    true,
	// FraudDetector primitive catalog (entity-type, label, outcome, list,
	// variable) — pure leaves, edges flow inward via event-type.
	"aws:frauddetector:entity-type": true,
	"aws:frauddetector:label":       true,
	"aws:frauddetector:list":        true,
	"aws:frauddetector:outcome":     true,
	"aws:frauddetector:variable":    true,
	// Cases domain is parent of children; children resolve to it but it
	// has no outbound refs.
	"aws:cases:domain": true,
	// Detective graph parent + member already wired (member→org); graph
	// itself has no outbound refs.
	"aws:detective:graph": true,
	// GameLift catalog (build/script/matchmaking-rule-set/location are
	// summary-only; container-group-definition refs ECR but image dispatch
	// not in scope).
	"aws:gamelift:build":                      true,
	"aws:gamelift:script":                     true,
	"aws:gamelift:location":                   true,
	"aws:gamelift:matchmaking-rule-set":       true,
	"aws:gamelift:container-group-definition": true,
	// Panorama, ground-station summaries (List-only, Tier C1 deferred).
	"aws:panorama:application-instance":          true,
	"aws:panorama:package":                       true,
	"aws:ground-station:config":                  true,
	"aws:ground-station:dataflow-endpoint-group": true,
	"aws:ground-station:mission-profile":         true,
	// IoTWireless — per Tier C1.4 verify, Get ops add no scanned-type
	// cross-refs for these 9 subtypes.
	"aws:iotwireless:device-profile":                 true,
	"aws:iotwireless:service-profile":                true,
	"aws:iotwireless:fuota-task":                     true,
	"aws:iotwireless:multicast-group":                true,
	"aws:iotwireless:network-analyzer-configuration": true,
	"aws:iotwireless:partner-account":                true,
	"aws:iotwireless:task-definition":                true,
	"aws:iotwireless:wireless-gateway":               true,
	"aws:iotwireless:wireless-device-import-task":    true,
	// SES catalog/leaves (mailmanager rule-set/relay/traffic-policy/
	// address-list bodies are leaves once ingress-point fans out to them;
	// configuration-set, contact-list, dedicated-ip-pool, template,
	// custom-verification-email-template, multi-region-endpoint, tenant
	// — pure config).
	"aws:ses:configuration-set":                  true,
	"aws:ses:contact-list":                       true,
	"aws:ses:custom-verification-email-template": true,
	"aws:ses:dedicated-ip-pool":                  true,
	"aws:ses:template":                           true,
	"aws:ses:multi-region-endpoint":              true,
	"aws:ses:tenant":                             true,
	// Backup catalog/audit (framework/report-plan/restore-testing-plan
	// have no outbound refs in summary).
	"aws:backup:framework":                 true,
	"aws:backup:report-plan":               true,
	"aws:backup:restore-testing-plan":      true,
	"aws:backup:restore-testing-selection": true,
	"aws:backup:tiering-configuration":     true,
	// AuditManager built-in catalog rows (most ManagedByProvider, but
	// types stay leaf-source either way).
	"aws:auditmanager:control":   true,
	"aws:auditmanager:framework": true,
	// Application catalog primitives.
	"aws:appflow:connector":                                      true,
	"aws:appintegrations:application":                            true,
	"aws:appintegrations:data-integration":                       true,
	"aws:appstream:app-block":                                    true,
	"aws:appstream:directory-config":                             true,
	"aws:appstream:stack":                                        true,
	"aws:appstream:user":                                         true,
	"aws:appsync:api":                                            true,
	"aws:appsync:domain-name":                                    true,
	"aws:appsync:graphql-api":                                    true,
	"aws:apigateway:api-key":                                     true,
	"aws:apigateway:client-certificate":                          true,
	"aws:apigateway:domain-name-access-association":              true,
	"aws:apigatewayv2:api":                                       true,
	"aws:appconfig:application":                                  true,
	"aws:appconfig:deployment-strategy":                          true,
	"aws:appconfig:extension":                                    true,
	"aws:apprunner:auto-scaling-configuration":                   true,
	"aws:apprunner:observability-configuration":                  true,
	"aws:appmesh:mesh":                                           true,
	"aws:application-autoscaling:scalable-target":                true,
	"aws:applicationsignals:grouping-configuration":              true,
	"aws:applicationsignals:service-level-objective":             true,
	"aws:aps:anomaly-detector":                                   true,
	"aws:aps:resource-policy":                                    true,
	"aws:aps:rule-groups-namespace":                              true,
	"aws:arc-region-switch:plan":                                 true,
	"aws:arc-zonal-shift:autoshift-observer-notification-status": true,
	"aws:b2bi:capability":                                        true,
	"aws:b2bi:partnership":                                       true,
	"aws:b2bi:profile":                                           true,
	"aws:b2bi:transformer":                                       true,
	"aws:budgets:budget":                                         true,
	"aws:budgets:budget-action":                                  true,
	// Amplify UI builder tooling (config-only).
	"aws:amplify-ui-builder:component": true,
	"aws:amplify-ui-builder:form":      true,
	"aws:amplify-ui-builder:theme":     true,
	"aws:amplify:domain":               true,
	// Lambda code-signing-config / layer-version-permission / permission
	// are config strings; capacity-provider has no scanned target type.
	"aws:lambda:capacity-provider":        true,
	"aws:lambda:code-signing-config":      true,
	"aws:lambda:layer-version":            true,
	"aws:lambda:layer-version-permission": true,
	"aws:lambda:permission":               true,
	// Resource catalog (Service Catalog / Resilience Hub).
	"aws:resilience-hub:app":                      true,
	"aws:resilience-hub:resiliency-policy":        true,
	"aws:servicecatalog:product":                  true,
	"aws:servicecatalog:service-action":           true,
	"aws:servicecatalog:tag-option":               true,
	"aws:servicecatalog:accepted-portfolio-share": true,
	// Inspector2 filter/CIS — leaves.
	"aws:inspector2:filter":                           true,
	"aws:inspector2:cis-scan-configuration":           true,
	"aws:inspector2:code-security-integration":        true,
	"aws:inspector2:code-security-scan-configuration": true,
	// Misc.
	"aws:accessanalyzer:analyzer":                       true,
	"aws:acm-pca:permission":                            true,
	"aws:athena:data-catalog":                           true,
	"aws:athena:work-group":                             true,
	"aws:athena:named-query":                            true,
	"aws:athena:prepared-statement":                     true,
	"aws:codestar-notifications:notification-rule":      true,
	"aws:securityhub:hub":                               true,
	"aws:securityhub:hub-v2":                            true,
	"aws:securityhub:standard":                          true,
	"aws:securityhub:security-control":                  true,
	"aws:securityhub:insight":                           true,
	"aws:securityhub:configuration-policy":              true,
	"aws:securityhub:organization-configuration":        true,
	"aws:securityhub:standards-subscription":            true,
	"aws:securityhub:policy-association":                true,
	"aws:securityhub:finding-aggregator":                true,
	"aws:securityhub:aggregator-v2":                     true,
	"aws:securityhub:automation-rule":                   true,
	"aws:securityhub:automation-rule-v2":                true,
	"aws:securityhub:connector-v2":                      true,
	"aws:redshift:cluster-parameter-group":              true,
	"aws:redshift:event-subscription":                   true,
	"aws:redshift:scheduled-action":                     true,
	"aws:redshift:integration":                          true,
	"aws:redshift:endpoint-authorization":               true,
	"aws:redshift:endpoint-access":                      true,
	"aws:rds:db-engine-version":                         true,
	"aws:rds:option-group":                              true,
	"aws:rds:db-cluster-parameter-group":                true,
	"aws:rds:event-subscription":                        true,
	"aws:elasticache:parameter-group":                   true,
	"aws:elasticache:security-group":                    true,
	"aws:elasticache:user":                              true,
	"aws:elasticbeanstalk:environment":                  true,
	"aws:emr-serverless:application":                    true,
	"aws:cloudfront:cache-policy":                       true,
	"aws:cloudfront:origin-request-policy":              true,
	"aws:cloudfront:response-headers-policy":            true,
	"aws:cloudfront:origin-access-control":              true,
	"aws:cloudfront:cloud-front-origin-access-identity": true,
	"aws:cloudfront:public-key":                         true,
	"aws:cloudfront:trust-store":                        true,
	"aws:cloudfront:anycast-ip-list":                    true,
	"aws:cloudfront:key-value-store":                    true,
	"aws:cloudfront:connection-function":                true,
	"aws:config:aggregation-authorization":              true,
	"aws:config:retention-configuration":                true,
	"aws:config:evaluation-form-version":                true,
	"aws:config:configuration-aggregator":               true,
	"aws:config:conformance-pack":                       true,
	"aws:config:organization-config-rule":               true,
	"aws:config:remediation-configuration":              true,
	"aws:control-tower:landing-zone":                    true,
	"aws:controltower:landing-zone":                     true,
	"aws:dms:certificate":                               true,
	"aws:dms:data-provider":                             true,
	"aws:s3express:directory-bucket":                    true,
	"aws:s3express:bucket-policy":                       true,
	"aws:s3outposts:bucket":                             true,
	"aws:s3outposts:endpoint":                           true,
	"aws:s3outposts:access-point":                       true,
	"aws:s3outposts:lifecycle-configuration":            true,
	"aws:s3tables:table-bucket":                         true,
	"aws:s3tables:namespace":                            true,
	"aws:s3tables:table":                                true,
	"aws:s3tables:table-bucket-policy":                  true,
	"aws:s3tables:table-policy":                         true,
	"aws:opensearchserverless:access-policy":            true,
	"aws:opensearchserverless:lifecycle-policy":         true,
	"aws:opensearchserverless:security-config":          true,
	"aws:opensearchserverless:security-policy":          true,
	"aws:opensearchserverless:vpc-endpoint":             true,
	"aws:opensearchserverless:collection-group":         true,
	"aws:greengrass:connector-definition":               true,
	"aws:greengrass:core-definition":                    true,
	"aws:greengrass:device-definition":                  true,
	"aws:greengrass:function-definition":                true,
	"aws:greengrass:group":                              true,
	"aws:greengrass:logger-definition":                  true,
	"aws:greengrass:resource-definition":                true,
	"aws:greengrass:subscription-definition":            true,
	"aws:greengrass-v2:component-version":               true,
}
