-- 016_rfc3339_scan_timestamps.sql
--
-- Deliberately empty. v0.31.0 shipped this file as a data migration that
-- rewrote scans.started_at, scans.finished_at and scan_checkpoints.updated_at
-- from the zoneless "YYYY-MM-DD HH:MM:SS" nowExpr emitted before v0.31.0 into
-- the RFC3339 it emits now. The rewrite was removed in v0.31.1 and the version
-- kept as a placeholder, because a version already recorded in
-- schema_migrations is skipped -- reusing 16 for anything else would apply on
-- a fresh store and be silently skipped on one that ran v0.31.0.
--
-- Two reasons the rewrite is gone, and the second is the blocking one.
--
-- Readers do not need it. store.ParseTimestamp accepts both shapes and
-- store.ToRFC3339 converts, so a store written by an older binary -- an
-- existing file, a restored backup -- reads correctly with no rewrite. The
-- migration was a tidiness pass, not a correctness fix.
--
-- And it cannot run where it was wanted. disco-saas puts every tenant schema
-- behind FORCE ROW LEVEL SECURITY with a policy reading
-- current_setting('app.workspace_id'), while its migration runner opens this
-- store scoped to a tenant and no workspace. FORCE subjects the table owner to
-- the policy, so any DML here raises 42704 ("unrecognized configuration
-- parameter") on every already-provisioned tenant schema and takes the whole
-- rolling-migration pass down with it. A fresh provision is unaffected --
-- disco migrations run before that FORCE is applied -- which is why this
-- passed every test and failed on the first real upgrade.
--
-- So a store keeps whatever shape its rows were written in, mixed or not, and
-- a consumer needing one uniform shape gets it by re-provisioning rather than
-- by rewriting rows under a policy this connection cannot satisfy.
